### ISSUE TITLE
Support anonymous functions in the Graph

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#10]
Something like Java lambda functions or C++ lambda expressions, such as:
```
SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, [](int preverify_ok, X509_STORE_CTX *x509_ctx) {
    return 1;
  });
```

- [x] Create a class representing the graph node. Extend from FunctionDeclaration? Is it a FunctionDeclaration without name?
- [x] Assign a handler in CDT to parse it
- [x] Assign a handler in JavaParser to parse it
- [ ] Adjust CFG passes to handle it

**Comment by konradweiss** [comment]
As long as the cfg and eog are only intra-procedural the will not have to be changed. The only issue that i see may be the node type: a declaration used as a parameter.
