### ISSUE TITLE
`variable` and `iterable` from `ForEachStatement` are not connected in DFG

### ISSUE THREAD

**Issue by seelchen** [Fraunhofer-AISEC/cpg#1006]
# Unexpected behavior

When analyzing code with a for each loop, there is no dataflow from the `iterable` to the `variable` of the `ForEachStatement`. The `variable` also has `UninitializedValue` as `initializer` which might be related to the missing dataflow.

# Example

```
class For {
    public void forIterator() {
        int[] a = {1,2,3,4,5};
        for(int j : a) {
            System.out.println(j);
        }
    }
}
```

# Changes to the configuration

```
TranslationConfiguration.builder()
            .defaultPasses()
            .defaultLanguages()
            .codeInNodes(true)
```

**Comment by oxisto** [comment]
Thanks for catching that. I have actually never seen this strange `UninitializedValue` expression. Seems to be a left over from some early days and should be removed.

**Comment by z2Z6** [comment]
Hi @oxisto ,
Could you have a plan to add the dataflow from the `variable`(`VariableDeclaration`) of `ForEachStatement` to its `DeclaredReferenceExpression` in  `ForEachStatement`. Now the dataflow from `iterable` to variable(`DeclarationStatement`) may has little significance.

**Comment by oxisto** [comment]
> Hi @oxisto ,
> Could you have a plan to add the dataflow from the `variable`(`VariableDeclaration`) of `ForEachStatement` to its `DeclaredReferenceExpression` in `ForEachStatement`. Now the dataflow from `iterable` to variable(`DeclarationStatement`) may has little significance.

I'll refer to the dataflow specialists @konradweiss and @KuechA :)

**Comment by KuechA** [comment]
Good catch, I'll look into it
