### ISSUE TITLE
`conditions` in `LoopScope` is always empty

### ISSUE THREAD

**Issue by seelchen** [Fraunhofer-AISEC/cpg#1012]
`conditions` is described in the documentation as a list of the conditions of the loopStatement. However, the conditions are never added so it always returns an empty list.

**Comment by seelchen** [comment]
As a quick fix I added the branch `add-loop-scope-conditions`.

**Comment by oxisto** [comment]
> As a quick fix I added the branch `add-loop-scope-conditions`.

Thanks. Can you make a PR out of it? then we can discuss it.
