### ISSUE TITLE
CPG infers new function declaration when integer argument is castable

### ISSUE THREAD

**Issue by keremc** [Fraunhofer-AISEC/cpg#1045]
# Unexpected behavior

When you call a function that takes a non-builtin integer type like `size_t` as a parameter, if the parameter value isn't already the expected type, CPG infers a new function declaration.

This is problematic when performing an analysis on the call graph, since I cannot inspect the definition of the called function in all cases.

# Code of interest

```c
// foo.h

#include <stdlib.h>
void foo(size_t);

// foo.c

void foo(size_t n) { }

// bar.c

#include "foo.h"

int main(int argc, char **argv)
{
        foo(argc);         // Infers a new function.
        foo((size_t)argc); // References the right function in the graph.
}
```

# Configuration

In cpg-console:

```kotlin
import java.io.File
import de.fraunhofer.aisec.cpg.frontends.CompilationDatabase
import de.fraunhofer.aisec.cpg.TranslationConfiguration
import de.fraunhofer.aisec.cpg.TranslationManager
val db = CompilationDatabase.fromFile(File("compile_commands.json"))
val translationConfiguration = TranslationConfiguration.builder()
    .defaultLanguages()
    .useCompilationDatabase(db)
    .sourceLocations(db.sourceFiles)
    .defaultPasses()
    .loadIncludes(true)
    .build()
val translationManager = TranslationManager.builder().config(translationConfiguration).build()
val translationResult = translationManager.analyze().get()
```

**Comment by oxisto** [comment]
Thanks for reporting this! Looks like an issue with typedefs (which are a still a mess). After tackling naming in v6 we are now having a closer look at call resolving and typing in the next version.
