### ISSUE TITLE
fullName property is incomplete when using namespaces

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#1070]
# Unexpected behavior

The namespace is missing in the `fullName` property of the type node.
For c++, the default namespace within a function definition is the namespace of function itself.
The cpg does not take this into account and creates a new type, outside the namespace.

![image](https://user-images.githubusercontent.com/2060591/215191609-f2f904cd-2c6f-470a-9b0f-7cb83a047312.png)

# Code of interest

```c++
namespace ABC {
        struct A {
        };
        void foo();
        void bar(ABC::A a);
};

void ABC::foo() {
        A a;
        bar(a);
}

void ABC::bar(ABC::A a) {
}

```

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

None

# Changes to the configuration

None

**Comment by oxisto** [comment]
Actually, the problem is even worse, since the C++ frontend incorrectly determines that `ABC::foo` and `ABC::bar` are *methods* of a (non-existing) class `ABC`; where in reality they are only scoped to the namespace `ABC` and are *functions*.
