### ISSUE TITLE
More thorough testing

### ISSUE THREAD

**Issue by Masrepus** [Fraunhofer-AISEC/cpg#116]
The test suite will be analyzed for feature coverage and updated/extended to cover the newest capabilities our graph has. Some tests are still only rather superficial concerning the results that are expected from the graph, e.g. they were made at a time where we did not have some call and variable resolving capabilities. Other parts of the CPG are still more or less untested, so additional tests will be created to make sure that we have a consistent state when introducing new features

**Comment by konradweiss** [comment]
We will close this issue for now as testing by now has reached an acceptable state and this issue does not reference any concrete missing tests that one could tackle to close the issue
