### ISSUE TITLE
Questions about current EOG implementation for method bodies / returns

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#1185]
I am currently trying to model the `defer` statement in Go, which executes code before the function returns.

 In order to do that I was looking at the current way the EOG is modelled in a function with multiple return paths, such as this:

```go
func main() {
	do()
	if len(os.Args) == 2 {
		return
	}

	fmt.Println("Still here, yay!")
}
```

The `return` at the end of the body is ommited. The graph looks like this:

<img width="807" alt="Screenshot 2023-05-28 at 10 47 51" src="https://github.com/Fraunhofer-AISEC/cpg/assets/12459061/e42ab552-609a-4693-bda5-ef2753dd72f6">

It seems that the explicit return (green node) in the `if` is the last EOG node in this branching path and the call expression in the last line (because no explicit return in this path) is connected to the function body (blue node). I would somehow assume that both paths should somehow converge again in the end?

If I add an explicit return, it seems that both paths end in a return and no EOG edge is created to the body; also no "convergence"

<img width="778" alt="Screenshot 2023-05-28 at 10 52 54" src="https://github.com/Fraunhofer-AISEC/cpg/assets/12459061/4954565c-8c37-454b-883b-f67ce2b26e74">

**Comment by KuechA** [comment]
I'm surprised that there's no implicit return statement in the first case. Did you filter it out? I quickly checked if this might get lost because the `ControlFlowSensitiveDFGPass` removes implicit return statements if they are not necessary but it doesn't affect the result (in particular not in this case but even if the print and return were in an `else` branch).

Of course, we could model such a merging point by additional EOG edges to the body or to the function declaration but I'm not sure if this would affect other analyses/passes/iteration methods which might currently rely on the return being the last node in the EOG.

Finally, if we would model an interprocedural CFG/EOG, I assume that the merging point would probably be the node after the call to this function.

**Comment by oxisto** [comment]
> I'm surprised that there's no implicit return statement in the first case. Did you filter it out? I quickly checked if this might get lost because the `ControlFlowSensitiveDFGPass` removes implicit return statements if they are not necessary but it doesn't affect the result (in particular not in this case but even if the print and return were in an `else` branch).

It seems that implicit return statements are added by either the parser or the language frontend. I know that the JavaParser adds it directly on the AST level. For Go I now added it in the frontend. Each frontend behaves differently here. Should we harmonise this somehow?

What is the point of *removing* the statement?

> 
> Of course, we could model such a merging point by additional EOG edges to the body or to the function declaration but I'm not sure if this would affect other analyses/passes/iteration methods which might currently rely on the return being the last node in the EOG.
> 
> Finally, if we would model an interprocedural CFG/EOG, I assume that the merging point would probably be the node after the call to this function.

**Comment by KuechA** [comment]
> What is the point of removing the statement?

I should be more precise: If there's code like `if(...) {... return; } else {... return; }`, there would be an additional implicit return statement inserted by the frontend after the else branch which is unnecessary and unreachable. The pass removes implicit return statements again if all branches reaching it already contain a return statement.

**Comment by oxisto** [comment]
> > What is the point of removing the statement?
> 
> I should be more precise: If there's code like `if(...) {... return; } else {... return; }`, there would be an additional implicit return statement inserted by the frontend after the else branch which is unnecessary and unreachable. The pass removes implicit return statements again if all branches reaching it already contain a return statement.

Ah ok, got it.
