### ISSUE TITLE
CPG Relationship Types:DFG,EOG

### ISSUE THREAD

**Issue by niuzhi** [Fraunhofer-AISEC/cpg#119]
Hello,
DFG,EOG detailed meaning，I don't understand these releationship type,can you help me to explain?
thank you very much.

**Comment by JulianSchuette** [comment]
Yes, documentation is still a bit scarce - we are just getting started with it ([here](https://www.codyze.io/docs/)), but details on the CPG are still missing.

`DFG` means Data Flow Graph and represents edges from _definitions_ of a variable to _usages_ of that variable.

`EOG` means Evaluation Order Graph and represents edges between (executable) AST nodes in the order they would be executed when running the code.
