### ISSUE TITLE
StackOverflowError in subtype listening system

### ISSUE THREAD

**Issue by morbitzer** [Fraunhofer-AISEC/cpg#1194]
Hey everyone, 

when trying to launch the cpg-neo4j, I get a `java.lang.StackOverflowError`. 
See the full log output [here](https://github.com/Fraunhofer-AISEC/cpg/files/11663656/log.txt).
[This](https://github.com/Fraunhofer-AISEC/cpg/files/11663680/code.txt) is the file I supplied as parameter. 

With `cpg-console`, the error looks slightly different: 

```
[...]
17:57:00,100 WARN  Util code.c:9574:50: Did not find a declaration for int64_t
17:57:00,102 WARN  Util code.c:9580:57: Did not find a declaration for int64_t
17:57:00,934 WARN  Util code.c:9634:59: Did not find a declaration for int64_t
18:12:59,259 INFO  MeasurementHolder TranslationManager: Translation into full graph done in 986182 ms
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at Line_18.<init>(Line_18.kts:1)
java.lang.NullPointerException: Cannot invoke "Line_18.getResult()" because "this.$$earlierScripts[17]" is null
        at Line_19.<init>(Line_19.kts:1)
```

Thanks for your help!

**Comment by peckto** [comment]
As a workaround, you can try to run only a subset of the analysis steps (passes).
E.g.
```
cpg-neo4j --custom-pass-list=TypeHierarchyResolver,VariableUsageResolver,CallResolver,TypeResolver,ImportResolver --save-depth=4 code.c
``` 
This of course gives you not the full graph, but maybe its better than nothing.

Unfortunately, after running cpg successfully we will run in some problems related to the Neo4j import:
- large numbers are not supported by the mapper (unsigned long) 
- recursion error (thus need for `--save-depth=` which will result in missing nodes in the neo4j db)
- transaction max size of 3GB - this can be changed in neo4j server settings

**Comment by KuechA** [comment]
#1268 should fix the problem with the type listeners but other problems do remain with this file
