### ISSUE TITLE
Missing DFG/EOG information for Python

### ISSUE THREAD

**Issue by CodingDepot** [Fraunhofer-AISEC/cpg#1235]
Nodes created by analyzing Python source code have empty datastructures for the properties `prevDFG`, `nextDFG`, `prevEOG` and `nextEOG`.

**Comment by maximiliankaul** [comment]
This is most likely a problem with the order in which passes are executed. We have improved the system some time ago with the introduction of annotations on passes which enforce the execution order (see [order](https://github.com/Fraunhofer-AISEC/cpg/tree/main/cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/order)). My understanding from an offline conversation is that you are using an old version of the CPG and most likely the order of passes in your setup is broken.
I suggest to fix the order in which you register passes in your old setup or update to a newer version of the CPG and make your passes dependent on the required DFG/EOG passes. Please let me know if you need any further help.
