### ISSUE TITLE
readme out of date?

### ISSUE THREAD

**Issue by e-shreve-ti** [Fraunhofer-AISEC/cpg#1271]
I noticed the following statements in the top-level [readme](https://github.com/Fraunhofer-AISEC/cpg/blob/main/README.md) which seem to not be correct:

1. Experimental Languages: "are not included as gradle submodules by default." However, the gradle.properties.example file has the experimental languages enabled. This leads to build failures if the dependencies are not installed, if someone attempts to build the system by using the content of the example file.
2. Contributing: "We are currently discussing the implementation of a Contributor License Agreement (CLA). Unfortunately, we cannot merge external pull requests until this issue is resolved." However, there is a [CONTRIBUTING.md](https://github.com/Fraunhofer-AISEC/cpg/blob/main/CONTRIBUTING.md) file which describes how to contribute and it implies a CLA will be presented when opening a PR.

**Comment by KuechA** [comment]
Hi @e-shreve-ti,

for 1), we changed our language-module system. Basically, the user has to specify which languages should be enabled for all languages. I adapted the readme to remove the misleading sentence.

For 2), the idea is to have a CLA and automatically enforce it but we're still in the process of implementing the CLA and the signing process. I added a warning with that note in the contributing md and hope that we will be able to (finally) resolve this issue soon...
