### ISSUE TITLE
cpg-console gives error about kotlin version on translate

### ISSUE THREAD

**Issue by e-shreve-ti** [Fraunhofer-AISEC/cpg#1272]
I built the CPG Console as described in the cpg-console readme.md file. I tried this on two machines, both were windows 10 with Adoptium JDK 17.0.8.7. I used the repo tag v7.1.2.

After copying the cpg-console folder from the install folder created by the build to a location with a shorter path, I am able to start cpg-console. However, when running ":tr src/test/resources/array.cpp", I get the following errors in the console:

ERROR Class 'de.fraunhofer.aisec.cpg.TranslationConfiguration' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from C:/tools/cpg-console/lib/cpg-core.jar!/de/fraunhofer/aisec/cpg/TranslationConfiguration.class (Line_1.kts:1:32)
ERROR Class 'de.fraunhofer.aisec.cpg.TranslationManager' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
The class is loaded from C:/tools/cpg-console/lib/cpg-core.jar!/de/fraunhofer/aisec/cpg/TranslationManager.class (Line_2.kts:1:32)
ERROR Unresolved reference: evaluate (Line_7.kts:1:38)
ERROR Unresolved reference: allChildren (Line_8.kts:1:38)
ERROR Unresolved reference: ast (Line_9.kts:1:38)
ERROR Unresolved reference: dfgFrom (Line_10.kts:1:38)
ERROR Unresolved reference: byName (Line_11.kts:1:38)
ERROR Unresolved reference: body (Line_12.kts:1:38)
ERROR Unresolved reference: capacity (Line_13.kts:1:38)
ERROR Unresolved reference: printCode (Line_14.kts:1:40)
ERROR Unresolved reference: TranslationConfiguration (Line_16.kts:2:17)
ERROR Unresolved reference: TranslationManager (Line_17.kts:1:16)
ERROR Unresolved reference: config (Line_17.kts:1:52)
ERROR Unresolved reference: analyzer (Line_18.kts:1:14)
ERROR Unresolved reference: result (Line_19.kts:1:10)

# Stack trace

None

# Unexpected behavior

Errors as shown above.

# Code of interest
Unknown

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

None

# Changes to the configuration

None

**Comment by KuechA** [comment]
Hi @e-shreve-ti,

the problem is that we're meanwhile using a more recent kotlin version (1.9.0) whereas ki-shell got stuck with 1.7.1. In theory, it could be easily upgraded and we opened a PR in the repository.

**Comment by xinyanmyriam** [comment]
> Hi @e-shreve-ti,
> 
> the problem is that we're meanwhile using a more recent kotlin version (1.9.0) whereas ki-shell got stuck with 1.7.1. In theory, it could be easily upgraded and we opened a PR in the repository.

Hi @KuechA 
I still have this problem with the latest version. Can you please explain how to upgrade? Thanks!

**Comment by peckto** [comment]
The problem with the incompatible Kotlin version of `kishell` is solved upstream, but there is unfortunately no new release until now. As a workaround, you can compile `kishell` from source and link the `cpg-console` against the local build.
Therefore, you need to do two things:

## 1) build `kishell` local
I could not find any option to build `kishell` library with dependencies, you can add this option by editing the `pom.xml`:
```patch
diff --git a/ki-shell/pom.xml b/ki-shell/pom.xml
index 02fde69..a9dbac7 100644
--- a/ki-shell/pom.xml
+++ b/ki-shell/pom.xml
@@ -237,6 +237,9 @@
           <finalName>ki</finalName>
           <attach>true</attach>
           <basedir>${project.parent.basedir}</basedir>
+         <descriptorRefs>
+            <descriptorRef>jar-with-dependencies</descriptorRef>
+          </descriptorRefs>
         </configuration>
         <executions>
           <execution>
```

Then you can build `kishell` with Kotlin 1.9:
```
mvn -Dkotlin.version=1.9.0 -DskipTests install
``` 

## 2) build `cpg-console` with local `kishell` version
You need to add the `mavenLocal` repository and the `kishell` snapshot version to the  `cpg-console/build.gradle.kts` file:
```patch
diff --git a/cpg-console/build.gradle.kts b/cpg-console/build.gradle.kts
index e0ff207b6..01455b4a8 100644
--- a/cpg-console/build.gradle.kts
+++ b/cpg-console/build.gradle.kts
@@ -52,6 +52,10 @@ tasks.withType<Test> {
     }
 }
 
+repositories {
+  mavenLocal()
+}
+
 dependencies {
     // CPG
     api(projects.cpgAnalysis)
@@ -59,5 +63,5 @@ dependencies {
 
     implementation(libs.kotlin.script.runtime)
     implementation(libs.kotlin.coroutines.core)
-    implementation(libs.kotlin.ki.shell)
+    implementation("org.jetbrains.kotlinx:ki-shell:0.5.3-SNAPSHOT:jar-with-dependencies")
 }
``` 

Then you can build and use the `cpg-console`:
```
./gradlew installDist
./cpg-console/build/install/cpg-console/bin/cpg-console
ki-shell 0.5.3-SNAPSHOT/1.9.0
type :h for help
[0] :tr ./cpg-console/src/test/resources/array.cpp
...
[19] :ls
val config: de.fraunhofer.aisec.cpg.TranslationConfiguration
val analyzer: de.fraunhofer.aisec.cpg.TranslationManager
val result: de.fraunhofer.aisec.cpg.TranslationResult!
val tu: de.fraunhofer.aisec.cpg.graph.declarations.TranslationUnitDeclaration
[20] 
```
