### ISSUE TITLE
Regression: Semantics of RecordDeclaration has changed

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#135]
With the revamped type system after version 1.4.2, a few things have changed which break the API/assumptions:

The semantics of `RecordDeclaration` has changed. Previously, it was _"a C++ union/struct/class or Java class that is declared in the analyzed source code"_. Now it is that, **plus**  _"any class/union/struct that is a supertype of the declared classes"_. This does not really make sense, because for any Record that is not _declared_  in the analyzed scope, the attributes of `RecordDeclaration` do not make sense: `methods`, `constructors`, `fields`, `importStatements` etc. cannot be filled. 

All clients of CPG will now have to distinguish between different "types" of `RecordDeclarations`: those that are "real" declarations and can be used as before and those that are only "implicit" Records whose attributes are not available and return null.

Is that change intended? It seems to make life for CPG clients more complicated and dilutes the semantics of `RecordDeclaration`.

See this example where `java.lang.Object` is a `RecordDeclaration` but obviously not declared in the analyzed scope.

![recorddecl](https://user-images.githubusercontent.com/1555755/86367286-0ab7b680-bc7c-11ea-9174-cc227a1954bf.png)

**Comment by Masrepus** [comment]
It's actually not just supertypes of classes declared in the analyzed files, but more generally any classes that are used in the analyzed files but whose declarations are somewhere else that is not in scope of the analysed files. So, java.lang.Object is an implicit superclass of every java class, thus used in the code, but not declared in our analysed files. I would think that this behavior is beneficial, e.g. also method calls to methods that we don't have in our scope are routed to dummy methods. This signals that we do know about their existance, as they are needed by some part of the analyzed program, we just don't have their explicit declaration ready. And in this case, the current system doesn't differentiate between unknown methods of known classes and unknown methods of unknown ones.
