### ISSUE TITLE
Regression: Superfluous TranslationUnits

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#136]
With the revamped type system after version 1.4.2, a few things have changed which break the API/assumptions:

Attached to the new "implicit" `RecordDeclaration` nodes (see bug #135) is an `unknown declarations` `TranslationUnit`. It obviously does not refer to any existing file (TranslationUnit) and provides no value.

For clients of CPG, this complicates things as it breaks the assumption that every `TranslationUnit` refers to an existing (analyzed) file.

Is that change intended and what is it good for? How are clients expected to handle `TransationUnits` that do not refer to actual files?

![recorddecl](https://user-images.githubusercontent.com/1555755/86367467-45215380-bc7c-11ea-90c8-24878e09a63c.png)

**Comment by Masrepus** [comment]
This unknown declarations TU has been there long before the type system update, it just wasn't that visible, as it only exists for classes that are not present in the analysed files, like java.lang.Object. In order to reach the behavior described in #135, that we have record declarations for unknown classes, we need some place to store them, in order to be able to reach them from the graph root. Our current graph roots are translation units, thus the unknown declarations TU as a container for dummy records

**Comment by JulianSchuette** [comment]
I understand. In 1.4.2 this was not present yet. The thing is - it makes CPG very unpleasant to use and complicates client code. A client now cannot simply assume that a `RecordDeclaration` is actually present in code and it cannot assume that a `TranslationUnit` actually exists.

This requires the client to a) know about the different forms and shapes in which a `RecordDeclaration` may appear and b) write complicated if-then constructs or clunky Gremlin queries than handle the different cases.
Also the assumptions about fields break - for example, a client cannot assume anymore that every `RecordDeclaration` has a non-null `location`. This requires changes throughout whole Codyze to check for nullness.

My suggestions would be to represent supertypes as `Type` nodes rather than `RecordDeclaration`. So, `java.lang.Object` becomes a `Type` that is referenced by the `RecordDeclaration` `Botan` in this case. This would also remove the need to have the _unknown declarations_ `TranslationUnit`.

**Comment by Masrepus** [comment]
This would only remove a single instance of unknown declarations. Even if supertypes are only present as types, any situation where a method is called or statically imported from a class that is unknown, dummies are still created.
I would suggest to rather fix the nullness issues, e.g. set an unknown record's location to a proper unknown one. Concerning the problems with record declarations and translation units not being present in the code, I don't really see where this could be problematic. It has the same effect as just an empty file or an empty class. Wouldn't codyze just skip over those?

**Comment by Masrepus** [comment]
Closing this as we fixed the dummy creation behavior already, thus no unknown declarations TUs are created anymore
