### ISSUE TITLE
Regression: Type classes are missing default constructor, breaks OGM

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#137]
With the revamped type system after version 1.4.2, a few things have changed which break the API/assumptions:

When converting back a serialized graph from the DB into Java objects, the object-graph-mapper (OGM) assumes that all deserialized objects have a default constructor. See https://github.com/Fraunhofer-AISEC/codyze/blob/1c861b3b47f59bde797eb06d779cfd156f815ca7/src/main/java/de/fraunhofer/aisec/crymlin/connectors/db/OverflowDatabase.java#L345

This assumption does not hold anymore for `PointerType`, `FunctionPointerType`, `ReferenceType` and prevents a CPG from being loaded from the DB.

**Comment by Masrepus** [comment]
Should work now. I made the constructors private in order to still enforce consistent API behavior, while giving the OGM the ability to instantiate the object via reflection

**Comment by JulianSchuette** [comment]
Great, thank you!
