### ISSUE TITLE
Label from abstract classes are not persisted to Neo4j

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#1373]
Abstract classes are not recognized as sources for labels anymore, while labels are still added to a node if the super class can be instantiated. Bellow we can see that a `ConstructorDeclaration` node has the labels `MethodDeclaration` and `FunctionDeclaration` but is missing the important `Declaration` label. This prevents queries to identify by the abstract types `Statement`, `Expression`, `Declaration`, `Type`, etc.

![image](https://github.com/Fraunhofer-AISEC/cpg/assets/12885000/a3b8d1d7-1e9b-46ff-bf39-5c7a808e70b3)

**Comment by oxisto** [comment]
Closed by #1374
