### ISSUE TITLE
Factory method for Types for cpg > 1.4.2

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#138]
In versions 1.4.2 and lower, clients of CPG could create a `Type` from the string they would retrieve from a vertice's property.

For example: 
```
String s = (String) q.V()....property("type").next();
Type t = Type.createFrom(s);
```

With the new type system - is there any similar convenience method? Or is it not needed anyway because types are deserialized from the graph in the form of individual nodes anyway?

**Comment by Masrepus** [comment]
That is now `TypeParser.createFrom(s)`
