### ISSUE TITLE
Incorrect Handling of Escaped Values

### ISSUE THREAD

**Issue by morbitzer** [Fraunhofer-AISEC/cpg#1408]
When parsing the value of Literals in `handleLiteralExpression`, escaped values are handled incorrectly. For example, if `ctx` is `\0`, only the `\` will be parsed and assigned to `lk_char_constant ` instead of the entire value.

**Comment by oxisto** [comment]
Do you have a code example where an integer is \0? I am a bit confused :)

**Comment by oxisto** [comment]
> Not sure why would it have to be an Integer? Take this example: `if ((char)s == '\0')`
> 
> Here, I end up with a Literal with the value `\` instead of `\0`

Ah, I misread handleLiteral for handleInteger. Ok thanks for the example.
