### ISSUE TITLE
Frontend cannot assign type to modulo operation

### ISSUE THREAD

**Issue by robinmaisch** [Fraunhofer-AISEC/cpg#1444]
Hello, CPG team,
Currently, in `de.fraunhofer.aisec.cpg.frontends.Language`, the modulo operator `%` is not handled in the method `propagateTypeOfBinaryOperation`, which causes BinaryOperator nodes with the operatorCode `%` to be assigned the `UNKNOWN` type, at least using the `JavaLanguage` . That should be a quick bug to fix, I think.

Cheers!

**Comment by oxisto** [comment]
> Hello, CPG team, Currently, in `de.fraunhofer.aisec.cpg.frontends.Language`, the modulo operator `%` is not handled in the method `propagateTypeOfBinaryOperation`, which causes BinaryOperator nodes with the operatorCode `%` to be assigned the `UNKNOWN` type, at least using the `JavaLanguage` . That should be a quick bug to fix, I think.
> 
> Cheers!

Hi! Would you be able to supply a PR for this?

**Comment by robinmaisch** [comment]
I'd be happy to, see #1449

**Comment by oxisto** [comment]
Fixed by https://github.com/Fraunhofer-AISEC/cpg/pull/1449
