### ISSUE TITLE
Java Frontend: EnumDeclarations do not get any content other than entries

### ISSUE THREAD

**Issue by robinmaisch** [Fraunhofer-AISEC/cpg#1445]
Hello CPG team,
the `de.fraunhofer.aisec.cpg.frontends.java.DeclarationHandler` ignores the `members` of `enumDecl` in the method `handleEnumDeclaration`, so any new `EnumDeclaration` does not get any fields, methods, constructors that it may need.
Import statements are also not considered, unlike for records.

I copied and adapted the relevant parts of `handleClassOrInterfaceDeclaration` (lines ~227-303) over to `handleEnumDeclaration`, and that seemed to work quite well as a start, but I could not get it to work completely in the end.
I hope you can have a look into it.

**Comment by konradweiss** [comment]
Hi :) Thanks for reporting the Issue. I will look into it and find out what the best option is there. I assume you mean in the Java language Frontend?

**Comment by konradweiss** [comment]
If you have a specific piece of code that shows the issue I'd love to test it out.

**Comment by konradweiss** [comment]
Thanks for that :) if you already have something that is not finished but shows an approach that you would follow you can submit a draft PR and signal what is missing or still not working.

**Comment by robinmaisch** [comment]
It turned out my approach did work, it was only my test that was wrong. Have a look :)
