### ISSUE TITLE
Name parsing of generic datatypes

### ISSUE THREAD

**Issue by robinmaisch** [Fraunhofer-AISEC/cpg#1453]
The function `parseName` of `Name` is currently not well suited well to parse FQNs that contain type arguments.
For example, the String "java.util.Optional<java.lang.String>" comes out as
parts = {"java", "util", "Optional<java", "lang", "String>"}

I suggest this: instead of splitting the FQN by a delimiter, it could be matched against a pattern describing the parts that should be kept together:
`(\\w+(?:<[\\w\\., <>]+>)?)` describes a pattern that should work well in Java, C++, and Rust, if I am not mistaken.
It would part `"java.util.Optional<java.lang.String>"` into the matches `{"java", "util", "Optional<java.lang.String>"}` and even
`"java.util.Optional<java.util.Map<java.lang.String, java.lang.Integer>>"` into `{"java", "util", "Optional<java.util.Map<java.lang.String, java.lang.Integer>>"}`.

In Go and Python, it seems that generic arguments are given in between square brackets. In Go, there seem to be other extensions to the type system that I am not really familiar with.

The language-specific characters for type arguments could be stored in the respective Language object, and the regular expression could be built dynamically from that, I suppose. 

I am specifically talking about in `ObjectType`s here, `FunctionType`s may be a whole story altogether.

**Comment by konradweiss** [comment]
Thats a good Idea. We should indeed use a generics delimiter for type arguments that we store in the language frontend. However, we probably should separate the type name `java.util.Optional` and the list of generic arguments `<java.lang.String>`.

**Comment by oxisto** [comment]
I would actually try to avoid going down this route... `parseName` is designed to parse *names*, not *types*! In case you end up with a "name" like `java.util.Optional<java.lang.String>` my suspicion is that at some point you were using a `toString` representation of a type instead of using the type directly. Native java parser types are converted using the `typeOf` function of the language frontend.
