### ISSUE TITLE
MemberCall inside LambdaExpression causes Parsing failure

### ISSUE THREAD

**Issue by robinmaisch** [Fraunhofer-AISEC/cpg#1455]
I have created a small failing Java example:

```
public class SquareMapper {

 	public int square(int i) { return i*i; }
	
	public List<Integer> squareAll(List<Integer> is) {
		return is.stream().map(i -> square(i)).toList(); 
	}
	
	public static void main(String[] args) {
		SquareMapper mapper = new SquareMapper();
		List<Integer> squares = mapper.squareAll(List.of(1,2,3,4));
		squares.forEach(sq -> System.out.println(sq));
	}

}
```

In `squareAll`, the instance method `square` is referenced, but the base `this` is left implicit.
In the Java frontend, this causes `ExpressionHandler.createImplicitThis()` (line 793ff.) to throw a ClassCastException because the `currentFunction` is a `FunctionDeclaration`, not a `MethodDeclaration`. The actual current method may be determined by iterating through the parents of the current scope, for example. Alternatively, the ScopeManager could offer a reference to the `currentMethod` in addition to the `currentFunction`. Or, `thisType` could be determined by the current record instead, I think.

If `this` is added as an explicit base for the `MemberCallExpression`, then the `MemberCallExpression` resolves correctly.

Remark: As JavaParser's `MethodReferenceExpr`s have no corresponding handler method mapped to them yet, replacing the `LambdaExpression` in line 6 by `this::square` results in a `ProblemExpression`.

I am very sorry to keep bugging you but I keep stumbling over these things, so I thought I might as well. Still, this project aids me greatly in my work, so thank you!

**Comment by konradweiss** [comment]
Hey, we are happy for every reported Issue especially when they are well documented :)

**Comment by oxisto** [comment]
> I am very sorry to keep bugging you but I keep stumbling over these things, so I thought I might as well. Still, this project aids me greatly in my work, so thank you!

No worries, unfortunately the Java language frontend is in a somewhat bad shape since it was one of the first ones and at the moment it is somewhat "unmaintained" since we have no dedicated person that takes care of it.

**Comment by konradweiss** [comment]
@robinmaisch I could not confirm the `ClassCastExpression` but found your argument that there should be better filtering in the current scope branch for a `FunctionScope` that actually represents a `MethodDeclaration` reasonable and implemented it. Could you confirm that it solves your Issue?
