### ISSUE TITLE
Utility log functions show up as wrong class

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#150]
The utility functions in the `Util` class show up as `Util` even through they use the logger from the original class, i.e. `VariableUsageResolver`.

https://github.com/Fraunhofer-AISEC/cpg/blob/1024f02164d547f961c0f2f3a6d0642410ef6711/src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java#L259-L262

which originates from 

https://github.com/Fraunhofer-AISEC/cpg/blob/b8801eb7f38b04e4254f0876e7e439cb56824c41/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java#L239

See output log

```
10:59:57,181 WARN  Util file:///C:/Users/ChristianBanse/Repositories/NetworkDemo/Source/NetworkDemo/NetworkDemoCharacter.cpp:123: Did not find a declaration for NULL
```

Not sure if this intended behavior in log4j so that it always prints the class where the log command is located rather than the class which created the logger. Although then I am confused why we need to explicitly create a `Logger` with a class.

This is not a big issue but it makes it hard to associate the log entry with the subcomponent of the library.

**Comment by KuechA** [comment]
Closed by  #1288
