### ISSUE TITLE
Fields of member expressions have an empty location

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#151]
Example code:
```
void SomeClass::SomeMethod()
{
	fieldObject->anotherField = true;
}
```

The `fieldObject->anotherField`  is correctly interpreted as a `MemberExpression`, but the member `anotherField` has an empty location

**Comment by oxisto** [comment]
While looking at this I came across another more fundamental issue. Why is the `member` field of a `MemberExpression` actually a `DeclaredReferenceExpression`? This creates an (in my opinion) unnecessary indirection. Actually, a member expression *is* basically a reference to a declared variable (with an additional base expression). Wouldn't it make more sense to inherit the member expression from a `DeclaredReferenceExpression` and use the `refersTo` fields instead of the `member` field?

**Comment by Masrepus** [comment]
The MemberExpression children are replaced by the actual field declarations when they are resolved, so it actually removes this indirection during runtime. But maybe it would be better to store member, base and their respective types internally instead of using DeclaredReferences, not sure

**Comment by oxisto** [comment]
Ahh I see. This resolution is partly broken too btw, because it always assume that the base of the `MemberExpression` is a field, which is not necessary, since the base can be everything, also a local variable or a function parameter. This is currently handled differently for `MemberExpression`s and `DeclaredReferenceExpression` in the `VariableUsageResolver` - which could be removed if one inherits from the other. Let's discuss this on the next CPG dev meeting.
