### ISSUE TITLE
There is a logic error in ValueEvaluator.

### ISSUE THREAD

**Issue by HaHarden** [Fraunhofer-AISEC/cpg#1527]
There is a logic error in `de.fraunhofer.aisec.cpg.analysis.ValueEvaluator#handleConditionalExpression`.

# testcase

```java
public void test() {
        int a = 1;
        a = a != 1 ? 2 : a;
        System.out.println(a);
}
```

When outputting the value of reference 'a', it should equal 1, but the result is 2.

**Comment by oxisto** [comment]
Oh, it looks like the value evaluator stupidly just compared the lhs (a) and res (1) of the condition using `==` regardless of the actual operator used 🙈 

https://github.com/Fraunhofer-AISEC/cpg/blob/bb92f3eb1a51c6b2a7fa1a45df5dd2d0108dff1c/cpg-analysis/src/main/kotlin/de/fraunhofer/aisec/cpg/analysis/ValueEvaluator.kt#L365-L369
