### ISSUE TITLE
Python: how to handle imports

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1535]
How should we handle imports in Python? The current approach (`VariableDeclaration` without fqn) is not satisfactory and should be improved. What is the _correct_ way to model this in the CPG?

- Import Alias
- FQN
- Multiple imports in one `import_stmt`
- Type: class? variable? ...?
- relative module paths
- import `*`

@KuechA re-started this discussion.

**Comment by oxisto** [comment]
Probably similar as I do it in go, but the whole system probably needs to be overhauled. Also slightly related to #1533

`import * from X` is basically the same as `using namespace X` in C++
import aliases also handled in Go with the `aliases` property in the scope manager, but this is a rather ugly hack

**Comment by oxisto** [comment]
We can start working on this, once #1536 is merged.
