### ISSUE TITLE
Non-deterministic error: FieldDeclaration created instead of VariableDeclaration

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#16]
The following C++ code is part of a test. In most cases it works, however sometimes and non-deterministically, the CPG represents `foo` as a `FieldDeclaration` of class `Test`, which is obviously wrong and fails the constant resolution.

```
class Test {
public:
 int call(int a) {
  return a + 1;
 }
};

int main() {
  int foo = 1;
  foo = (1,2,3,4,42);
  Test t;
  t.call(foo);
}
```
The attached pictures show two graphs created by two test runs of exactly the same code. The graph containing the (dark) green `FieldDeclaration` is wrong.

![cpgfailure-2](https://user-images.githubusercontent.com/1555755/71008791-7e7fe080-20e9-11ea-8bea-e66ed784710b.png)
![cpgfailure-1](https://user-images.githubusercontent.com/1555755/71008792-7f187700-20e9-11ea-8fc4-93d229bccd84.png)

**Comment by oxisto** [comment]
FYI contrary to the comment in the new unit test, this actually has nothing to do with variable (list) initialization but is rather just a use of the „comma operator“, i.e. a BinaryOperator with the op „,“ which _evuluates_ all expressions in the parenthesis in order and assignees the last used expression to the operation itself.

**Comment by titze** [comment]
cannot reproduce on my machine.  
How often do you have to run the test? 
Does sth like

```java
for(int i = 0; i < 1000; i++) {
         testLocalVariables();
     }
```
always fail on your machine, or do I need to start separate tests?
