### ISSUE TITLE
Inconsistent return type for getProperty(Properties.BRANCH)

### ISSUE THREAD

**Issue by morbitzer** [Fraunhofer-AISEC/cpg#1611]
`getProperty(Properties.BRANCH)` returns a boolean when the start node is a simple IfStatement such as `if ( 1 == 1 )`. However, if the IfStatement is more complex, such as `if ((a != 0) && (b != 0))`, it returns a collection, still with a single element.. 

This should be changed so that the same type is returned for both cases.

**Comment by oxisto** [comment]
I assume that we except a set all the time? Since it can potentially be a set?
