### ISSUE TITLE
Python `type_comments`

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1649]
Investigate and make it work.

```
ast.parse = parse(source, filename='<unknown>', mode='exec', *, type_comments=False, feature_version=None)
    Parse the source into an AST node.
    Equivalent to compile(source, filename, mode, PyCF_ONLY_AST).
    Pass type_comments=True to get back type comments where the syntax allows.
```

**Comment by oxisto** [comment]
After some investigation, it seems that type comments are mainly used in backporting type functionality into Python 2. Python 3 uses type hints and type annotations and we actually already use them at least for function return types and argument types.

**Comment by oxisto** [comment]
Let's keep this issue specifically about type comments. I created an umbrella issues for everything in PEP-484
