### ISSUE TITLE
Overhaul Pass Annotations

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1670]
We have identified the following passes with questionable annotations:

- [ ] GoExtraPass: does it need type information?
- [ ] ReplaceCallCastPass: should CXXExtraPass be a soft dependency?
- [ ] execute before: should it default to `soft`?
- [ ] GoExtraPass: this currently has "double" dependencies with the dfg and symbol resolver -> can we get rid of one?
- [ ] PDG depend on dynamicinvkeresovler?
- [x] @maximiliankaul : neo4j -> PrepareSerialization is missing in the mermaid graph -> it's not in the graph because there are no dependencies from/to the pass.

In general: we should fix some rules on how to use the dependency annotations. I basically see two options:
- use them as much as possible (and make use of the `soft` flag)
  - this makes the graph explode
  - this most accurately reflects the real dependencies and protects us in case we change/remove some passes in the future
- use them as little as possible
  - smaller graph / less annotations (no double dependencies on EOG and DFG for example, as the DFG already implies a EOG dependency)
  - risk: if we assume another pass is present for our ordering assumptions but this pass is actually missing -> wrong order
  - we should define a minimum set of passes which we always assume to be present if we decide to go this way.

**Comment by oxisto** [comment]
I would exclude the java* passes from this and track this in a separate issue.
