### ISSUE TITLE
Python: improve scoping

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1677]
Scanning Python code results in countless `ScopeManager unknown: Could not find the scope ...` warnings.This should be investigated and fixed.

**Comment by oxisto** [comment]
To reproduce, clone https://github.com/openstack/nova and run `./gradlew :cpg-neo4j:run --args="../../nova/ --no-neo4j"`

**Comment by maximiliankaul** [comment]
> To reproduce, clone https://github.com/openstack/nova and run `./gradlew :cpg-neo4j:run --args="../../nova/ --no-neo4j"`

Or, for significantly shorter execution time, `glance` 2-3 minutes instead of 1.5 hours.
