### ISSUE TITLE
Refers-to broken

### ISSUE THREAD

**Issue by titze** [Fraunhofer-AISEC/cpg#17]
E.g. for `testLocalVarsCpp` in branch `julian-16-wrong-fields`, there are `FieldDeclarations` for `x`, `foo`, and `a`.

The problem might be in `VariableUsageResolver.resolveLocalVarUsage`

**Comment by oxisto** [comment]
Is this fixed in master or was this just a problem in another branch? @titze

**Comment by titze** [comment]
if I see it correctly, this is alredy merged into master with https://github.com/Fraunhofer-AISEC/cpg/pull/19 
can be closed imo
