### ISSUE TITLE
Support multiple vars in a forloop

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1702]
```python
for a, b in foo:
  pass
```
should be correctly modeled in the CPG.

We decided to introduce a dummy variable in the loop itself (as the CPG does not support multiple vars here) and then introduce an `a, b = dummy` assignment at the top of the body.

:warning:  This is "easy" for known variables but we have to consider where to store declarations for new variables.

**Comment by oxisto** [comment]
> ⚠️ This is "easy" for known variables but we have to consider where to store declarations for new variables.

Actually this would be already taken care of in the existing code of the assignment expression / the python extra pass. That's the added advantage of using this "fake" assignment here.
