### ISSUE TITLE
C++ generics with elaborated type specifiers fail to parse

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#171]
The following: `TypeParser.createFrom("Array<struct Node>", true)` will create a generic type with a type parameter of type `"structNode"`. This seems to happen here, because of some reason this function here will remove all the whitespace within the generic block. Therefore, the type parser cannot correctly identity the `struct` as an elaborated type specifier (which is normally ignored). However, simply removing the function also does not work since then it is parsed as seperate typeblocks and things really start to go wrong :(

https://github.com/Fraunhofer-AISEC/cpg/blob/3f3542015dd6c989b8f8274b89478dfe67922126/src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java#L261-L300

**Comment by vfsrfs** [comment]
The TypeParser needs to remove the spaces from the generics, as spaces are used to split up the type string later on. Am I right assuming that the correct generic would be an ObjectType with the Name "Node" instead of "structNode". Would it therefore be sufficient to ignore elaborated types in the generics and just remove the keyword?

**Comment by oxisto** [comment]
Simple answer: yes

More complicated answer: If I read https://en.cppreference.com/w/cpp/language/type correctly, a type that just references a type, that is just declared but never defined, i.e. using `struct Node` without having a `struct Node {}` definition beforehand would actually be an incomplete type, but I am not sure if we want to follow the standard this strictly. I guess for us it is more efficient to say that this is an object type.

**Comment by vfsrfs** [comment]
I agree. For our purposes it is probably more convenient to abstract from the standard, and just make use of the IncompleteType, when there is no other possibility to represent a type in a differeny way. In this case an ObjectType would be expected.
