### ISSUE TITLE
Nested functions are not added to AST

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#1736]
In python it is possible to nest functions in functions. For some reason, they do not end up in the AST at all. I stumbled across this once I tried to implement #1713

**Comment by maximiliankaul** [comment]
Seems to be an issue outside of the Python front-end. I can see the front-end handling nested functions and creating the appropriate nodes. Will investigate further...

**Comment by maximiliankaul** [comment]
Once resolved: remember to test this: https://github.com/Fraunhofer-AISEC/cpg/pull/1735#discussion_r1784834098, too.

**Comment by oxisto** [comment]
It seems that also the EOG for nested functions is missing.
