### ISSUE TITLE
Issues with declaration (statements)

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#178]
There are two issues with declaration statements or declaration sequences. The first one is, that it seems that all declarations in a sequence are assigned the same type. However, this is not entirely correct, if you look at:
```cpp
int *a, b;
```

This actually should declare two variables, one with type `int*` and one with type `int`. In our CPG, both variables have type `int*`, which is incorrect.

Second issue is regarding class types that are declared within a simple declaration, i.e.
```cpp
class A {

} myA;
```

While the CPG correctly parses the type of the variable `myA` as `A`, the declaration statement (if used in a function) only contains a variable declaration for `myA`, but it should also contain a record declaration for `A`.

**Comment by Masrepus** [comment]
Haha what, you can declare classes in this way? 😅

**Comment by oxisto** [comment]
Yeah... to be honest, I also did not know that before looking at the C++ reference. Weird language.

**Comment by oxisto** [comment]
Ok it looks like my original test was wrong and the first issue is already solved, the second one is still there though.
