### ISSUE TITLE
JVM Frontend not working with class or jimple or jar files

### ISSUE THREAD

**Issue by surya-malleswar-chinta** [Fraunhofer-AISEC/cpg#1790]
_cpg % ./gradlew installDist                                                  
Type-safe project accessors is an incubating feature.

> Configure project :
Java frontend is disabled
C/C++ frontend is disabled
Go frontend is disabled
Python frontend is disabled
LLVM frontend is disabled
TypeScript frontend is disabled
Ruby frontend is disabled
JVM frontend is enabled_

Enabled JVM frontend, when trying to parse .class, .jimple or .jar file through this command

_./cpg-neo4j/build/install/cpg-neo4j/bin/cpg-neo4j --no-neo4j --export-json=cpg-export.json ./cpg-language-jvm/src/test/resources/jimple/helloworld/HelloWorld.jimple_

19:01:17,002 INFO  MeasurementHolder TranslationManager: Executing Language Frontend
19:01:17,012 INFO  TranslationManager Parsing /Users/suryamalleswarchinta/GIT_REPOS/cpg/cpg-language-jvm/src/test/resources/jimple/helloworld/HelloWorld.jimple
**ERROR TranslationManager Found no parser frontend for HelloWorld.jimple**

**Comment by oxisto** [comment]
It seems that the neo4j app was missing the registration of the JVM language frontend. I will supply a fix for that.

**Comment by oxisto** [comment]
Should work now with the PR. Please note that the JVM language frontend needs a "top-level" directory specified, so you need to use 
```
./cpg-neo4j/build/install/cpg-neo4j/bin/cpg-neo4j --no-neo4j --export-json=cpg-export.json --top-level ./cpg-language-jvm/src/test/resources/jimple/ ./cpg-language-jvm/src/test/resources/jimple/helloworld/HelloWorld.jimple
```
