### ISSUE TITLE
Add child evaluation order directly to nodes

### ISSUE THREAD

**Issue by Masrepus** [Fraunhofer-AISEC/cpg#18]
Even before constructing the EOG, we sometimes need to ensure that we visit nodes in their specific evaluation order. Otherwise things like #16 happen and it might not quite clear what the actual cause for nondeterministic behavior is. Thus we need to add a method to `Node` that allows the retrieval of direct AST children in their exact evaluation order instead of some arbitrary sorting.

Example use case: When resolving variables, we could encounter things like the following:
```
public class X {
    private int field = 0;

    public int foo() {
        field = 42;  // refers to the actual field
        int field = 123;
        return field;  // refers to the shadowing local var!
    }
```

Here, the correctness of any variable resolving relies on the correct visiting order of the statements.

**Comment by konradweiss** [comment]
Nodes can be sorted according to there position in the file using the NodeComparator. This, however, is not always the right solution as there are some rare cases of right-to-left evaluation (Function Args). In which cases is it necessary to have the evaluation order before the EOG construction where we cannot postpone that "pass" after the EOG-construction?

**Comment by konradweiss** [comment]
As there is no reason to not execute the EOGPass before the VariableUsageResolver we will close this Issue. The NodeComparator can be used for file position based order. If the evaluation order is need there is no way around the EOG
