### ISSUE TITLE
Improve AsyncOrNot

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#1800]
- https://github.com/Fraunhofer-AISEC/cpg/pull/1795/files#diff-72d2f49193f6f7691f493c9ed57932cfdaef14d58f15c747e148a7906607c50cR250
- https://github.com/Fraunhofer-AISEC/cpg/pull/1795/files#diff-72d2f49193f6f7691f493c9ed57932cfdaef14d58f15c747e148a7906607c50cR296

I don't like the `as? Python.AST.BaseStmt` checks here. However, the underlying problem is that the interface chain goes up to `WithLocation` (https://github.com/Fraunhofer-AISEC/cpg/blob/78d41f9074009ea80a453e544a5dea6120c05390/cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/Python.kt#L165) instead of `Python.AST`. We should redesign the `Python.AST` structure here, so that we do not need the `as?` when working with `AsyncOrNot` nodes.

**Comment by KuechA** [comment]
Closed by #1799
