### ISSUE TITLE
Clarify behaviour of loadIncludes

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#181]
https://github.com/Fraunhofer-AISEC/cpg/blob/6af6499ae50cfc1ea8b51631a0d17bcf146b415a/src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java#L58-L59

According to the documentation of loadIncludes, includes such as header files will be parsed but not included to the CPG. However, at first glance it seems that that either the  documentation or the behaviour is incorrect 

If loadInclude is set to false, the include provider for CDT will be set to an empty files provider, effectively hindering CDT to parse the header file at all. Or do I miss another step where they are considered?

So this looks ok-ish (although I am not sure if `getContainingFilename` will point to the header file if it is included through a chain:

https://github.com/Fraunhofer-AISEC/cpg/blob/9231e141b9b5b043fd59371ce21b80a52c7124ab/src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java#L82-L90

But this does not look ok then:

https://github.com/Fraunhofer-AISEC/cpg/blob/ab802001b88dd1def0914f0c46bee6e86a60f415/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java#L275

_Originally posted by @oxisto in https://github.com/Fraunhofer-AISEC/codyze/pull/35#issuecomment-664987729_

**Comment by JulianSchuette** [comment]
Codyze is assuming the documented behavior (which also seems to make more sense):

- `loadIncludes` determines whether include files will be "loaded" into the CPG. If it is set to `true`, the respective `TranslationUnits`and their AST childs will become part of the CPG. If it is set to `false`, the include files will be _parsed_ (so they still can be used for type resolution, for instance), but they will not become part of the CPG and thus, it will not be possible to find vulnerabilities/flaws in them
- `includePaths` dermines the path(s) containing include files.

There should be a test case for that.

**Comment by oxisto** [comment]
As agreed, we will parse all includes, but ignore all include files in the CPG, wherever they are.
