### ISSUE TITLE
Support for constant propagation

### ISSUE THREAD

**Issue by llooFlashooll** [Fraunhofer-AISEC/cpg#1830]
Hi folks, I really appreciate your work.

However, the doc of this repo says it supports constant propagation, while I cannot find the concrete code implementation as well as the corresponding test cases. Can you give me further instructions? Thank you!

**Comment by oxisto** [comment]
Hi! Thanks for your interest in our project. Closing this issue as you opened another question in the Q&A discussion about this (https://github.com/Fraunhofer-AISEC/cpg/discussions/1831).
