### ISSUE TITLE
Separate the concept of an AST subgraph and the members of a structure

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#184]
We currently have no explicit AST edges. The fact that a node is an AST-Child of another node is encoded in certain edges, e.g. lhs, rhs of a BinaryOperation. This however poses a problem with c++ and data structures. There a definition of a function can be done outside of the containing structure, but is part of the structures field. This specific case is currently solved over an indirection, a declaration in a class has a definition. However, we should discuss about an explicit AST subgraph, and whether this subgraph can be combined with Edge-Properties.

**Comment by KuechA** [comment]
Does #1116 close this issue?
