### ISSUE TITLE
References as indirections to avoid cycle on what we currently consider AST-edges

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#185]
In the past when a refersTo edge was resolved to a unique target the DeclaredReferenceExpression was removed and replaced by the target. This caused dublicates when creating a list of all children over the @ASTChildren-Annotation and even cycles. My current proposal is to keep this Reference Node in all cases or to discuss specific exceptions, e.g. `member` of `MemberExpression`

**Comment by oxisto** [comment]
Is this similar to https://github.com/Fraunhofer-AISEC/cpg/issues/151

**Comment by Masrepus** [comment]
Seems to be the same behavior that is described here. Isn't it currently the case that this replacement only happens for `MemberExpressions` and not for regular references?

**Comment by oxisto** [comment]
Seems to have been fixed by #213
