### ISSUE TITLE
TranslationManager support hpp files

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#202]
The TranslationManager seems not to detect C++ header files with the .hpp file extension.
Example:
```
11:13:23.876 [ForkJoinPool.commonPool-worker-3] ERROR de.fraunhofer.aisec.cpg.TranslationManager - Found no parser frontend for watchdog.hpp
```

**Comment by Masrepus** [comment]
Sorry, referenced the wrong issue :sweat_smile:

**Comment by oxisto** [comment]
Do you want to explicitly only analyze the hpp file or is it included in a cpp file? For the latter, make sure to enable `loadIncludes` in the translation manager and then the file should also be parsed.

**Comment by peckto** [comment]
I'm using:
```
val translationConfiguration = TranslationConfiguration.builder()
    .sourceLocations(*files)
    .topLevel(topLevel!!)
    .defaultPasses()
    .loadIncludes(true)
    .debugParser(true)
    .build()
```

In this case I wanted to analyze a cpp file and the cpp file included the hpp file. 
With the `loadIncludes` option, the hpp file indeed gets analyzed and loaded to the graph appropriate.
In this case, the Error message is misleading.

The other case, when analyzing a hpp file without being included is also interesting and could be relevant.
Do I need some other options in this case?
When having a `.h` and `.hpp` file (both not being included), only the `.h` file is loaded.
Probably the error message is related to this case.

**Comment by oxisto** [comment]
> I'm using:
> 
> ```
> val translationConfiguration = TranslationConfiguration.builder()
>     .sourceLocations(*files)
>     .topLevel(topLevel!!)
>     .defaultPasses()
>     .loadIncludes(true)
>     .debugParser(true)
>     .build()
> ```
> 
> In this case I wanted to analyze a cpp file and the cpp file included the hpp file.
> With the `loadIncludes` option, the hpp file indeed gets analyzed and loaded to the graph appropriate.
> In this case, the Error message is misleading.
> 
> The other case, when analyzing a hpp file without being included is also interesting and could be relevant.
> Do I need some other options in this case?
> When having a `.h` and `.hpp` file (both not being included), only the `.h` file is loaded.
> Probably the error message is related to this case.

There are two issues:

First one, is recognising `hpp` as a valid extension. This is easily fixed.

Second one. We probably want a switch, whether we want to handle `.h` or `.hpp` files as individual files (and thus translation units) or just analyse them, if they are included in a `cpp` file. The way we currently do it has the drawback, that if a folder contains a `.h` and `.cpp` (which includes the header file), we loop through all suitable files and parse them into the graph. Therefore, we would end up adding the contents of the header files twice - which you normally would not want. On the other hand, there might be a use case to handle header files as translation units on their own, i.e. if analysing a header-only library.

**Comment by peckto** [comment]
Yes, there are two independent issues.

Is the first been already addressed?

For the second, do i understand you right, that `.h` files which are also included by some `.c` file, get loaded twice and their content (eg. declarations) appear twice in the cpg? Does this behavior depend on the options `.loadIncludes(true)`?
Would it be possible, to parse `.h` and `.hpp` (and maybe `.h++`) only in case they are not included?
In this way, we do not need an extra switch and nothing appers twice in the graph.
Parsing include files can then only depend on the `.loadIncludes(true)` option.

**Comment by oxisto** [comment]
> Yes, there are two independent issues.
> 
> Is the first been already addressed?

Not yet, feel free to propose a PR ;-)

> 
> For the second, do i understand you right, that `.h` files which are also included by some `.c` file, get loaded twice and their content (eg. declarations) appear twice in the cpg? Does this behavior depend on the options `.loadIncludes(true)`?
> Would it be possible, to parse `.h` and `.hpp` (and maybe `.h++`) only in case they are not included?
> In this way, we do not need an extra switch and nothing appers twice in the graph.
> Parsing include files can then only depend on the `.loadIncludes(true)` option.

They would be loaded twice, if you specify a `directory` to scan, yes, because currently it goes through the directory and loads all "suitable" files.
 
If you only specify the `.c`/`.cpp` files, then they would only show up once. You can also directly parse `.h` files if you specify them directly.
