### ISSUE TITLE
How to deal with void being indicator for no arguments?

### ISSUE THREAD

**Issue by vfsrfs** [Fraunhofer-AISEC/cpg#208]
`void` can be used  to indicate that a function does not take any arguments, e.g. the following functions both have the same signature (no arguments):

```
void foo(void);
void foo2();
```

However, the graph shows that the function `foo` contains a parameter of type `void`. This may be also the case when dealing with function pointers.

![argument_graph](https://user-images.githubusercontent.com/44771450/91199832-b0c4f180-e6fe-11ea-90b8-6694a9ae7b6b.png)

Is this the desired behavior in order to stay as close as possible to the source code or would it instead be better to clearly indicate that the function `foo` does not take any argument by removing the void parameter in the graph?

**Comment by oxisto** [comment]
I would remove the void parameter. Guess its a weird behaviour of eclipse CDT, that it includes this as a parameter. `clang` for example also just removes the parameter in its AST:
```
|-FunctionDecl 0x7fe993851e18 <void.cpp:1:1, col:14> col:6 foo 'void ()'
`-FunctionDecl 0x7fe993851f20 <line:2:1, col:11> col:6 foo2 'void ()'
```
