### ISSUE TITLE
InitializerHandler::handleConstructorInitializer returns a ConstructExpression

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#21]
The `handleConstructorInitializer` handles a `CPPASTConstructorInitializer` this is an initialiser in the *declaration* of an constructor (and not the institution of it), and it incorrectly returns an `ConstructExpression`.

It is not quite clear what a `ConstructExpression` actually seems to be. In the `ExpressionHandler::handleObjectCreationExpr` it seems to be used as an `initializer` of a `NewExpression`.

**Comment by JulianSchuette** [comment]
To exemplify: This code ...

`const MyType my_variable(arg_0, arg_1);`

... is turned into a `VariableDeclaration` for `my_variable` with `type = const MyType` and an edge `INITIALIZER` pointing to the `ConstructExpression` (which does not have a `type` property).

Is this intended behavior?

**Comment by oxisto** [comment]
Nevermind, seems to be correct but really needs to be documented better.
