### ISSUE TITLE
ScopeManager scope not active errors

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#225]
Since maybe #198 i seem to get a lot of these errors:
```
Node of type class de.fraunhofer.aisec.cpg.graph.ConstructorDeclaration has a scope but is not active in the moment.
```

Sometimes, the same with a `MethodDeclaration`. The easiest way to trigger them is actually the `testRecordDeclaration` in `CXXLanguageFrontendTest`. They seem to occur if a node that was previously a `FunctionDeclaration` is later replaced by a method or a constructor but the scope map is never updated. Weirdly enough I thought that these errors were gone with my #179 PR, but they seem to have appeared again.

**Comment by oxisto** [comment]
Ah, looks like @konradweiss commented out this line in my `replaceNode` function, rendering it useless :) 

https://github.com/Fraunhofer-AISEC/cpg/blob/70e9ea4e94f160571e8526c06e0366550a0d0cd9/src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java#L429

Instead it seems you created this new `disconnectFromGraph` function but it won't achieve the same effect in the `handleMembers` function. It seems that we really need a test for checking the correct scope here.

**Comment by Masrepus** [comment]
`disconnectFromGraph` is actually something I introduced for handling the "swap-out" behavior used in the legacy implementation of `MemberExpression` resolving

**Comment by oxisto** [comment]
Ah, I see! So might not be necessary in this use case at all. Not sure why the line above was commented out, maybe a left over from some cleanup as part of #198. The PR should restore this old behaviour without braking anything.
