### ISSUE TITLE
Investigate use of PopulatedByPass annotation

### ISSUE THREAD

**Issue by Masrepus** [Fraunhofer-AISEC/cpg#233]
Currently, the `@PopulatedByPass` annotation is only assigned to the fields `constructor` and `instantiates` in `ConstructExpression`. Is there still / was there ever any use for this annotation? Depending on that, we should either adopt the annotation more consistently or just remove it entirely

**Comment by oxisto** [comment]
I think it was / is there purely for documentation reasons, so in this case we should probably adopt it more often.

**Comment by JulianSchuette** [comment]
Yes, it is not used by Codyze. But it would be nice if it would be documented in a consistent way. A Javadoc may do as well.
