### ISSUE TITLE
extern C statement missing

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#244]
For C++ code, it seems like, the `extern` statement is not parsed correctly.
Example:
```cpp
extern "C" {
    #include "foo.h" 
}
```
The header file `foo.h` is not parsed.

**Comment by oxisto** [comment]
Do you know if it not parsed (i.e. by CDT) or if the contents of the header file are not persisted in the graph?

**Comment by peckto** [comment]
Maybe "parsed" was misleading. Actually, I cannot distinguish between parsed by the CDT and persisted in the graph.
What I have observed is, that everything inside the `extern` statement is not available in the cpg graph.
Not available like, there have been no `#include` statement. Meaning, all declarations inside `foo.h` are missing.
