### ISSUE TITLE
Build-pattern style member calls are recognised as static call expressions

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#285]
i.e. 

```
target.path("/").get();
```

wrongly results in a `StaticCallExpression` with name `get` and fqn `target.path("/").get`. It should be a `MemberCallExpression` with further call expressions as a base.

**Comment by oxisto** [comment]
It seems that the `ExpressionHandler` wrongly expects that if the base is not resolvable to a variable declaration, that it is a static member call. Also the `member` field always seems to be a dummy declared ref instead of pointing to the function - or is that being done later?

https://github.com/Fraunhofer-AISEC/cpg/blob/2ef9a1cb2daa59a7a7d16fd8a7ce0768cc46f2e7/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java#L674-L681

**Comment by konradweiss** [comment]
> It seems that the `ExpressionHandler` wrongly expects that if the base is not resolvable to a variable declaration, that it is a static member call. Also the `member` field always seems to be a dummy declared ref instead of pointing to the function - or is that being done later?
> 
> https://github.com/Fraunhofer-AISEC/cpg/blob/2ef9a1cb2daa59a7a7d16fd8a7ce0768cc46f2e7/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java#L674-L681

I tried to find it but setMember is never called on the `MemberCallExpression` and only set via constructor in the Frontends.

The member is apparently used in the CallResolver to then resolve the call and safe the result to setInvokes. considering that the target of the call may not be unique in general, it makes sense that the member is only "the name". On the other hand one could draw a reference from the member to the most general function for the MemberCallExpression specifically
