### ISSUE TITLE
FQN of types and method names

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#29]
Seems to be very inconsistent. Some examples (can expand on this later):

- C++ namespaces, such as `std::string` are converted to Java-style `std.string`. Is this intentional? Looks very weird
- FQNs to methods in Java are indistinguishable to FQNs of types, i.e. the FQN for `println` is `java.io.PrintStream.println`. We could stick to the Javadoc-style of `java.io.PrintStream#println`. On the other hand C++ also does not really distinguish between types and method references.

**Comment by JulianSchuette** [comment]
> C++ namespaces, such as std::string are converted to Java-style std.string. Is this intentional? Looks very weird

Yes, FQNs should be unified across all frontend languages as otherwise the analysis would have to differentiate between different languages ( at a point where it is not aware of the frontend anymore). 

If there are inconsistencies or ambiguities that should be fixed.

**Comment by oxisto** [comment]
This can be considered fixed with #963
