### ISSUE TITLE
Incorrect resolution of method invocation in C++

### ISSUE THREAD

**Issue by vfsrfs** [Fraunhofer-AISEC/cpg#292]
The resolution of functions invocation in C++ does not work correctly. The code snippet below calls the function `printname` in the main function. This call should be resolved to the `MethodDeclaration` `printname` from the `Geeks` `RecordDeclaration`. Instead an implicit `FunctionDeclaration`  `printname` is created which is directly connected with the TranslationUnitDeclaration.

## Graph
<img width="604" src="https://user-images.githubusercontent.com/44771450/104012518-34fcaa80-51b0-11eb-9f17-384b0dfdc44b.png">

## Snippet
```
// C++ program to demonstrate
// accessing of data members

#include <bits/stdc++.h>
using namespace std;
class Geeks
{
    // Access specifier
    public:

    // Data Members
    string geekname;

    // Member Functions()
    void printname()
    {
       cout << "Geekname is: " << geekname;
    }
};

int main() {

    // Declare an object of class geeks
    Geeks obj1;

    // accessing data member
    obj1.geekname = "Abhi";

    // accessing member function
    obj1.printname();
    return 0;
}
```

**Comment by oxisto** [comment]
Wow, that is rather strange, since this is a pretty basic functionality and I naively would assume that we would have a unit test to check this Good catch

**Comment by oxisto** [comment]
Quick debugging notes: It seems that the call of `printname()` is handled by `CallResolver::handleNormalCall` when it should have been handled by `handleMethodCall`.

**Comment by vfsrfs** [comment]
Yes the else branch should be selected and `handleMethodCall` should be called. I think this is caused due to the fact, that the if statement checks for `curClass == null`. Since the main function is not inside a class, `currClass` is `null` and the ifstatement is true.

**Comment by vfsrfs** [comment]
Yes the else branch should be selected and `handleMethodCall` should be called. I think this is caused due to the fact, that the if statement checks for `curClass == null`. Since the main function is not inside a class, `currClass` is `null` and the ifstatement is true.
