### ISSUE TITLE
Resolution of static methods does not work

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#302]
Consider the following example:

```
struct Vector {
public:
  static float DistXY(const Vector& v1, const Vector& v2);

  float x, y, z;
};

float Vector::DistXY(const Vector& v1, const Vector& v2)
{
  return 2;
}

class Character {
public:
  void DoSomething();
};

void Character::DoSomething()
{
  Vector v1;
  Vector v2;

  Vector::DistXY(v1, v2);
}
```

The call to `Vector::DistXY` within `Character::DoSomething` should be resolved to a (static) call expression to `Vector::DistXY`. Instead it is resolved to a dummy method `Character:: DistXY`. This is possibly related to #292, but the proposed fix in #294 does not help in this case.

**Comment by vfsrfs** [comment]
This error is due to a mismatch in the function signature. In the MethodDeclaration the type of the parameters is correctly ReferenceTypes because of the `$` and in the call the parameters are ObjectTypes of type `Vector`.
