### ISSUE TITLE
Control Flow Pass Takes long

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#307]
The Control Flow Graph pass takes long or isn't even terminating for the following medium-sized Java file: https://gist.github.com/anon767/964becb5936abb91d6e4d8f707a5e214 .

Is there a possible bug or is this a performance issue simply due to the fact, that there are many (nested) conditional blocks?
Interestingly, removing all Setters starting from Line 740, solves this issue.

Thanks in advance

Edit://
CPG version: 3.2.0

**Comment by oxisto** [comment]
That sounds strange indeed. Can you please double-check that you are not on 3.3.0, because we updated to JavaParser 3.18.0 and this had a major bug that lead to a dead-lock (see #304). The 3.3.1 hotfix release reverts that. However 3.2.0 should still be on 3.17.0 anyway

This sounds similar, although the other deadlock was in an AST handler and not in the CFG pass.

**Comment by anon767** [comment]
Thanks for the quick response. I just tried CPG version 3.3.1. There, another error occurred to me:
```
 Unable to calculate the type of a parameter of a method call. Method call: addParameter("label", findString(label)), Parameter: findString(label)
```

The function is indeed not defined but this wasn't an issue with CPG version 3.2.0 (I guess that's because of the updated JavaParser). 
Could the flag "failOnError" in the TranslationConfiguration Class perhaps be used to circumvent this issue in the future?

Nevertheless, after removing the undefined methods, the CFG pass is still stuck with CPG version 3.3.1 . 
Strangely as before, the removal of the Setters causes the CFG pass to terminate.

**Comment by oxisto** [comment]
@konradweiss Have fun with this one ;)

**Comment by oxisto** [comment]
> Thanks for the quick response. I just tried CPG version 3.3.1. There, another error occurred to me:
> 
> ```
>  Unable to calculate the type of a parameter of a method call. Method call: addParameter("label", findString(label)), Parameter: findString(label)
> ```
> 
> The function is indeed not defined but this wasn't an issue with CPG version 3.2.0 (I guess that's because of the updated JavaParser).
> Could the flag "failOnError" in the TranslationConfiguration Class perhaps be used to circumvent this issue in the future?
> 
> Nevertheless, after removing the undefined methods, the CFG pass is still stuck with CPG version 3.3.1 .
> Strangely as before, the removal of the Setters causes the CFG pass to terminate.

This is indeed a bug introduced in 3.3.1, meh. We are catching the wrong exception here. Will fix that.

Could you provide some more details about the environment you are running this on, such as operating system, Java version, configuration of the translation manager and so on?

The example file runs fine on my MacBook Air M1 using Java 15 in a unit test in about 7s.

**Comment by anon767** [comment]
Alright here are my specs:
- MacBook pro-2020 and AWS EC2 (c5d.9xlarge) Ubuntu 18.04 
- Java tested with OpenJDK 15, OpenJDK 13, OpenJDK 8, Azul 13
- Gradle 6.8

My build.gradle:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // built-in
    java
    application
    
    id("com.diffplug.gradle.spotless") version "3.27.1"
    kotlin("jvm") version "1.4.30-RC"
}

application {
    mainClassName = "com.thecout.cpg.ApplicationKt"
}


group = "com.thecout.cpg"

extra["isReleaseVersion"] = !version.toString().endsWith("SNAPSHOT")

val mavenCentralUri: String
    get() {
        val releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2"
        val snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots"
        return if (project.extra["isReleaseVersion"] as Boolean) releasesRepoUrl else snapshotsRepoUrl
    }

repositories {
    mavenCentral()

    ivy {
        setUrl("https://download.eclipse.org/tools/cdt/releases/9.11/cdt-9.11.1/plugins")
        metadataSources {
            artifact()
        }
        patternLayout {
            artifact("/[organisation].[module]_[revision].[ext]")
        }
    }
}

tasks.withType<GenerateModuleMetadata> {
    enabled = false
}

tasks.withType<Sign>().configureEach {
    onlyIf { project.extra["isReleaseVersion"] as Boolean }
}

tasks.named("compileJava") {
    dependsOn(":spotlessApply")
}


java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11

    withSourcesJar()
    withJavadocJar()
}

val versions = mapOf(
        "junit5" to "5.6.0",
        "cpg" to "3.3.1"
)

dependencies {
    api("de.fraunhofer.aisec", "cpg", versions["cpg"])

    testImplementation("org.junit.jupiter", "junit-jupiter-api", versions["junit5"])
    testImplementation("org.junit.jupiter", "junit-jupiter-params", versions["junit5"])
    testRuntimeOnly("org.junit.jupiter", "junit-jupiter-engine", versions["junit5"])

    api("info.picocli:picocli:4.1.4")
    annotationProcessor("info.picocli:picocli-codegen:4.1.4")
    implementation(kotlin("stdlib-jdk8"))
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "15"
}

val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "15"
}

```
 
The TranslationManager Configuration:
```
        val translationConfiguration = TranslationConfiguration.builder()
                .sourceLocations(*filePaths)
                .topLevel(topLevel!!)
                .registerPass(FilenameMapper())
                .registerPass(TypeHierarchyResolver())
                .registerPass(JavaExternalTypeHierarchyResolver())
                .registerPass(ImportResolver())
                .registerPass(TypeResolver())
                .processAnnotations(true)
                .codeInNodes(true)
                .loadIncludes(loadIncludes)
                .registerPass(EvaluationOrderGraphPass()) // creates EOG
                .registerPass(ControlFlowGraphPass())
                .registerPass(CallResolver()) // creates CG
                .registerPass(VariableUsageResolver())
                .registerPass(ControlFlowSensitiveDFGPass())
                .debugParser(false)
                .failOnError(false)
```

**Comment by oxisto** [comment]
```
> 
> The Translation Configuration:
> 
> ```
>             val translationConfiguration = TranslationConfiguration.builder()
>                     .sourceLocations(file)
>                     .topLevel(topLevel.toFile())
>                     .loadIncludes(true)
>                     .defaultPasses()
>                     .registerPass(ControlFlowGraphPass())
> ```

I think the problem might be lying here. The `defaultPasses()` already includes the `ControlFlowSensitiveDFGPass`. If you then execute the (semi)-deprecated `ControlFlowGraphPass`, after that, things probably go wrong. Is there a particular reason you want the old `ControlFlowGraphPass` instead of the new one?

If you really need it then you need to get rid of the `defaultPasses` and replace it with

```
      registerPass(new TypeHierarchyResolver());
      registerPass(new JavaExternalTypeHierarchyResolver());
      registerPass(new ImportResolver());
      registerPass(new VariableUsageResolver());
      registerPass(new CallResolver()); // creates CG
      registerPass(new EvaluationOrderGraphPass()); // creates EOG
      registerPass(new TypeResolver());
      registerPass(new ControlFlowGraphPass());
      registerPass(new FilenameMapper());
```

The `FilenameMapper` should be executed last, so that all of the nodes have valid locations. We are working on a new dependency system for the passes, which might help with that.

**Comment by oxisto** [comment]
Wait, sorry for the mix-up. The `ControlFlowGraphPass` is replaced by the `EvaluationOrderGraphPass`. While they should (in theory) not interfere with each other, the `ControlFlowGraphPass` is not maintained any more and should be marked as deprecated. You can use the `EOG` edges to follow the "evaluation order", which is very similar to a control flow graph but more precise, i.e. it also includes individual arguments of a function call and not just the functions itself.

**Comment by anon767** [comment]
Ah well so the CFG Pass is not really maintained anymore. Then I will try to use the EOG for my purposes :) 

Thank you for your help, I will close this issue.
