### ISSUE TITLE
Implementation of Templates in the CPG

### ISSUE THREAD

**Issue by vfsrfs** [Fraunhofer-AISEC/cpg#319]
The purpose of this issue is to document the decisions @konradweiss and I made on how to implement CPP Templates.

The implementation of the CPP Templates will be split up into two parts: A first representation of the Template in the Graph and a Pass that refines the Template usage, with the same approach used by the CPP Compiler. The main reason for choosing this approach is the fact, that an extensive resolution of the templates leads to a more refined graph, but it might also increase the size of the graph considerably. Therefore, the refinement is implemented as a pass, in order to make the refinement optional if the graph size is too big.

Java Generics can also be modelled as a subset of CPP Templates and therefore the current Java Generics representation will be modified to be consistent with the CPP Templates approach. The main differences are:
1. Java Generics can only be applied on Classes, whereas CPP Templates can be applied on Classes and Functions

2. In Java the parameters of the classes can only be Types, compared to CPP Templates, where values can also be provided to the Template.

## Representation
To explain how Templates will be represented in the graph, we will be using the following snippet as an example. This snippet represent a template applied on a function, but this is sufficient as applying templates to classes is very similar.

Code:

```
#include <iostream>
using namespace std;

template <class T, int N>
T fixed_multiply (T val)
{
  return val * N;
}

int main() {
  std::cout << fixed_multiply<int,2>(10) << '\n';
  std::cout << fixed_multiply<float,3>(10.0) << '\n';
}
```

Graph:
![initial](https://user-images.githubusercontent.com/44771450/106276787-5d6c4780-6238-11eb-8bf2-4a6cdfa132d3.png)

As we can see, the graph now includes a new node called Template (exact naming is open for discussion) containing three outgoing edges. The first one is the `realization` edge to the function, which is implemented by the template. The second and third edges are `parameters`-Edges pointing towards the two parameters of the template. The first parameter is a ParameterizedType as introduced by #317 and defined in #293. This represents the abstract Type T and contains two edges two both types it has been initialized in the code (int and float). The second argument is a `ConstantDeclaration`, as the values passed to Templates must be known at compile time and therefore they must be constant. This node also contains `possibleInitialization`-Edges to the Literals that have been found in the initialization of the Template.

## Refinement Pass

As explained before, a more refined graph has a bigger size, since every usage of the Template leads to a custom function/class. However, a more refined graph is useful for the analysis of the code, since it may enable us to have a more exact resolution of the code (e.g. exact resolution of a call is possible since we now have type information).

Therefore, this pass modifies the graph and 'realizes' every usage of the Template following the same approach as the CPP Compiler.

Graph:
![pass](https://user-images.githubusercontent.com/44771450/106276833-6d842700-6238-11eb-956e-4b4a6bc45f8e.png)

As we can see in the graph above, now the template contains two `FunctionDeclaration`s (of the same function) with the different realizations, and each CallExpression invokes the correct realized `FunctionDeclaration`. Additionally, the `FunctionDeclaration`s now contain pointer to the exact values that were used to realize the template.

**Comment by oxisto** [comment]
Just for reference, this is the generated clang AST for the example:

```
|-FunctionTemplateDecl 0x7f904c049038 <template.cpp:4:1, line:8:1> line:5:3 fixed_multiply
| |-TemplateTypeParmDecl 0x7f904c048d50 <line:4:11, col:17> col:17 referenced class depth 0 index 0 T
| |-NonTypeTemplateParmDecl 0x7f904c048e10 <col:20, col:24> col:24 referenced 'int' depth 0 index 1 N
| |-FunctionDecl 0x7f904c048f98 <line:5:1, line:8:1> line:5:3 fixed_multiply 'T (T)'
| | |-ParmVarDecl 0x7f904c048ea0 <col:19, col:21> col:21 referenced val 'T'
| | `-CompoundStmt 0x7f904c049150 <line:6:1, line:8:1>
| |   `-ReturnStmt 0x7f904c049140 <line:7:3, col:16>
| |     `-BinaryOperator 0x7f904c049120 <col:10, col:16> '<dependent type>' '*'
| |       |-DeclRefExpr 0x7f904c0490e0 <col:10> 'T' lvalue ParmVar 0x7f904c048ea0 'val' 'T'
| |       `-DeclRefExpr 0x7f904c049100 <col:16> 'int' NonTypeTemplateParm 0x7f904c048e10 'N' 'int'
| |-FunctionDecl 0x7f904c0496c8 <line:5:1, line:8:1> line:5:3 used fixed_multiply 'int (int)'
| | |-TemplateArgument type 'int'
| | |-TemplateArgument integral 2
| | |-ParmVarDecl 0x7f904c0495d0 <col:19, col:21> col:21 used val 'int':'int'
| | `-CompoundStmt 0x7f904c82fe30 <line:6:1, line:8:1>
| |   `-ReturnStmt 0x7f904c82fe20 <line:7:3, col:16>
| |     `-BinaryOperator 0x7f904c82fe00 <col:10, col:16> 'int' '*'
| |       |-ImplicitCastExpr 0x7f904c82fde8 <col:10> 'int':'int' <LValueToRValue>
| |       | `-DeclRefExpr 0x7f904c82fd88 <col:10> 'int':'int' lvalue ParmVar 0x7f904c0495d0 'val' 'int':'int'
| |       `-SubstNonTypeTemplateParmExpr 0x7f904c82fdc8 <col:16> 'int'
| |         `-IntegerLiteral 0x7f904c82fda8 <col:16> 'int' 2
| `-FunctionDecl 0x7f904c82faf8 <line:5:1, line:8:1> line:5:3 used fixed_multiply 'float (float)'
|   |-TemplateArgument type 'float'
|   |-TemplateArgument integral 3
|   |-ParmVarDecl 0x7f904c82fa00 <col:19, col:21> col:21 used val 'float':'float'
|   `-CompoundStmt 0x7f904c82ff08 <line:6:1, line:8:1>
|     `-ReturnStmt 0x7f904c82fef8 <line:7:3, col:16>
|       `-BinaryOperator 0x7f904c82fed8 <col:10, col:16> 'float' '*'
|         |-ImplicitCastExpr 0x7f904c82fea8 <col:10> 'float':'float' <LValueToRValue>
|         | `-DeclRefExpr 0x7f904c82fe48 <col:10> 'float':'float' lvalue ParmVar 0x7f904c82fa00 'val' 'float':'float'
|         `-ImplicitCastExpr 0x7f904c82fec0 <col:16> 'float' <IntegralToFloating>
|           `-SubstNonTypeTemplateParmExpr 0x7f904c82fe88 <col:16> 'int'
|             `-IntegerLiteral 0x7f904c82fe68 <col:16> 'int' 3
`-FunctionDecl 0x7f904c0491c0 <line:10:1, line:13:1> line:10:5 main 'int ()'
  `-CompoundStmt 0x7f904c82fd78 <col:12, line:13:1>
```
