### ISSUE TITLE
Crash related to function pointer call

### ISSUE THREAD

**Issue by Masrepus** [Fraunhofer-AISEC/cpg#32]
Nondeterministic crash in CallResolver for this code:

```cpp
#include <iostream>

class A {
  public:
    void fun() {
      std::cout << "Hello" << std::endl;
    }

    int mainA() {
      A a;

      void (A::* f_ptr) () = &A::fun;
      a.fun();
      (a.*f_ptr)();
    }
};

int main() {
  A a;

  void (A::* f_ptr) () = &A::fun;
  a.fun();
  (a.*f_ptr)();
}
```
Additionally, some quick checks showed some further problems in this snippet:
- [x] `(a.*f_ptr)()` has name ".", which makes totally no sense
- [x] `a.fun()` is currently not resolved as the member call on class A that it actually is
- [x] Function pointer handling needs to be added to the call resolver
- [x] Tests for function pointer call resolving are needed

**Comment by oxisto** [comment]
For me it is still confusing why CDT is resolving this as the Binary Operator `.` instead of something like a field expression. Did you check how LLVM handles this?

**Comment by oxisto** [comment]
Here is the relevant part:
```
`-FunctionDecl 0x10f03c278 <line:11:1, line:17:1> line:11:5 main 'int ()'
  `-CompoundStmt 0x10f03c968 <col:12, line:17:1>
    |-DeclStmt 0x10f03c648 <line:12:3, col:6>
    | `-VarDecl 0x10f03c320 <col:3, col:5> col:5 used a 'A' callinit
    |   `-CXXConstructExpr 0x10f03c620 <col:5> 'A' 'void () throw()'
    |-DeclStmt 0x10f03c828 <line:14:3, col:33>
    | `-VarDecl 0x10f03c748 <col:3, col:30> col:14 used f_ptr 'void (A::*)()' cinit
    |   `-UnaryOperator 0x10f03c810 <col:26, col:30> 'void (A::*)()' prefix '&' cannot overflow
    |     `-DeclRefExpr 0x10f03c7e0 <col:27, col:30> 'void ()' CXXMethod 0x10f038b78 'fun' 'void ()'
    |-CXXMemberCallExpr 0x10f03c890 <line:15:3, col:9> 'void'
    | `-MemberExpr 0x10f03c860 <col:3, col:5> '<bound member function type>' .fun 0x10f038b78
    |   `-DeclRefExpr 0x10f03c840 <col:3> 'A' lvalue Var 0x10f03c320 'a' 'A'
    `-CXXMemberCallExpr 0x10f03c948 <line:16:3, col:14> 'void'
      `-ParenExpr 0x10f03c928 <col:3, col:12> '<bound member function type>'
        `-BinaryOperator 0x10f03c908 <col:4, col:7> '<bound member function type>' '.*'
          |-DeclRefExpr 0x10f03c8b0 <col:4> 'A' lvalue Var 0x10f03c320 'a' 'A'
          `-ImplicitCastExpr 0x10f03c8f0 <col:7> 'void (A::*)()' <LValueToRValue>
            `-DeclRefExpr 0x10f03c8d0 <col:7> 'void (A::*)()' lvalue Var 0x10f03c748 'f_ptr' 'void (A::*)()'
```

And this is actually something I would prefer as well. Is it important for us to distinguish this explicitly as a function pointer call expression? Or is it just a regular `MemberCallExpression` in this case? (and a regular call expression in any other?) I fear that we add too many different kind of call expressions that then are specific to the language.

**Comment by Masrepus** [comment]
The problem is that the member we would be calling is the function pointer variable and not the method itself. A normal `MemberCallExpression` has no dedicated `member` property but we rather use its name to identify the method to be called. For function pointer calls this is not sufficient, as we need to have the full member node (a `DeclaredReferenceExpression` in this case), as we need to traverse it until we get the actual declaration it refers to. For now I created a new class that has this dedicated field, as I was unsure how it would need to be handled for normal member calls. I will migrate it to the original `MemberCallExpression` and check whether I  can find a consistent solution for both normal member calls, C++ function pointer calls on base objects and C function pointer calls that do not have a base object.

**Comment by Masrepus** [comment]
If there are function pointers that are not called at some point, we currently have no way of telling which function exactly they are referencing (if there are multiple overloaded variants for a specific function name). The actual signature is only known at call-time. In order to represent this in the graph, we would need to have multiple outgoing `refers_to` edges from `DeclaredReferenceExpressions`. For now I will not do it this way but rather wait for dedicated function pointer types that should be added in #35. This will enable us to exactly pinpoint the correct target of a function pointer, as the desired signature is part of a function pointer's type
