### ISSUE TITLE
Missing equals/hashcode in PhysicalLocation and ArtifactLocation

### ISSUE THREAD

**Issue by armbruer** [Fraunhofer-AISEC/cpg#321]
The cpg library should consider usage scenarios like the following: Multiple analysis runs are done on the same or similar files and afterwards compared against each other. The results of these runs may contain many nodes which are expected to be equal but found to be not equal due to the identity comparison in ArtifactLocation and PhysicalLocation. To avoid this issue, equals/hashcode implementations should be provided in these classes.

**Comment by Masrepus** [comment]
Related to #177

**Comment by oxisto** [comment]
Closed as duplicate
