### ISSUE TITLE
File attribute for TranslationUnitDeclaration null

### ISSUE THREAD

**Issue by armbruer** [Fraunhofer-AISEC/cpg#322]
The file attribute for the TranslationUnitDeclaration is never set. This was probably forgotten here https://github.com/Fraunhofer-AISEC/cpg/blob/16031b65a2c09d90bc0121af13f2d19eefbdb9d9/src/main/java/de/fraunhofer/aisec/cpg/passes/FilenameMapper.java#L39.

**Comment by Masrepus** [comment]
Wouldn't that be somehow redundant, as the name attribute of a `TranslationUnitDeclaration` is exactly what would be stored in the `file` attribute?

**Comment by KuechA** [comment]
#702 closed this issue.
