### ISSUE TITLE
Wrong type set in newTypeIdExpression(...)

### ISSUE THREAD

**Issue by armbruer** [Fraunhofer-AISEC/cpg#323]
https://github.com/Fraunhofer-AISEC/cpg/blob/16031b65a2c09d90bc0121af13f2d19eefbdb9d9/src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java#L102

Here twice the variable type is used to set a type and referencedType is never used.
This should probably be setReferencedType(referencedType).

**Comment by konradweiss** [comment]
Thanks for creating the issue :)
