### ISSUE TITLE
RunTimeException not caught for second call to resolve() in handleMethodCallExpression()

### ISSUE THREAD

**Issue by dentoir** [Fraunhofer-AISEC/cpg#327]
In the current master version of CPG, catching `UnsolvedSymbolException` has been replaced with catching a `RunTimeException` because the newer JavaParser can now throw it and we want to catch it gracefully.

I think the fix implemented in commit https://github.com/Fraunhofer-AISEC/cpg/commit/fe7c17740246c6a5003140b8315331b94ab6cd69 also has to be applied to the catch statement here https://github.com/Fraunhofer-AISEC/cpg/blob/master/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.java#L697

This resolved the problem for me when running CPG on a large set of Java projects.

**Comment by oxisto** [comment]
Ah, good point, I fear we need to go through all `resolve()` calls and apply it there. Meh, I still don't know why they would bury a runtime exception deep down in the resolve instead of properly throwing an `UnsolvedSymbolException`

**Comment by oxisto** [comment]
Ok I am wondering why, we are calling resolve() in this case anyway, because the result is not used anyway.
