### ISSUE TITLE
The expression -2147483648 cannot be parsed

### ISSUE THREAD

**Issue by titze** [Fraunhofer-AISEC/cpg#34]
```java
int narf = -2147483648;
```

cannot be parsed, as Javaparser thinks the right side is a `UnaryExpression` (MINUS) containing a `IntegerLiteralExpression` (2147483648). 
We try to parse the Integer which is not in the Integer Range anymore -> `NumberFormatException`

We could directly parse a Unary containing an Integer as a negative Integer, but this would be a bit of a hacky fix

**Comment by oxisto** [comment]
Should we report this to http://github.com/javaparser/javaparser?

**Comment by oxisto** [comment]
To expand on this, it seems that JavaParser *always* parses negative numbers as an unary expression + literal. Meh.

**Comment by oxisto** [comment]
I had a look at what the java compiler actually does, and it would seem a good compromise: For the expression `-1`, it gets rid of the unary expression and represents it as a literal with the value `-1`. This would also allow us to quickly search for those literals. However the c/c++ compilers explicitly leave it as two expresions so this would already be a case where the two languages would defer. We can of course emulate this for C++ as well, but not sure if we then loose some info about possible under/overflow issues.

**Comment by oxisto** [comment]
Just FYI, this is currently on hold until at least https://github.com/javaparser/javaparser/pull/2485 is merged (and released), then I will work on a workaround for CDT and merge it into CPG

**Comment by oxisto** [comment]
CDT has similar issues parsing bigger values, i.e. unsigned int int. I've filed a bug report for this, but we will probably introduce some workaround in the meantime.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=559622
