### ISSUE TITLE
Type-System needs rework

### ISSUE THREAD

**Issue by titze** [Fraunhofer-AISEC/cpg#35]
The current way we parse and store types will likely not work in all cases, especially for C-Types.

Code like `static const char * const somearray[]` can currently not be parsed, and I am not sure if it can even be stored correctly in the adjustment and type-modifier

**Comment by Masrepus** [comment]
Once this is done, we need to remember to fix the fix the tests in `FunctionPointerTests` so that unused function pointers are expected to only point to the method variant that has the correct signature
