### ISSUE TITLE
How to Cite?

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#351]
Hey,

just a general question:
Is there a preferred way to cite this tool?
I'm using it in my research projects and want to reference it in my paper :)

Thanks in advance and regards

**Comment by oxisto** [comment]
I'll keep this open until we published the tech report and included the citation in the README

**Comment by copernico** [comment]
What I would do is to write a 4 pages technical description and put it on arxiv.org

**Comment by oxisto** [comment]
> What I would do is to write a 4 pages technical description and put it on arxiv.org

We are working on a little bit more detailed description, we are planning to release it end of April.

**Comment by anon767** [comment]
Any update to this? :)

**Comment by oxisto** [comment]
> Any update to this? :)

The paper we submitted is currently in review.

**Comment by oxisto** [comment]
In the meantime we could implement this: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by oxisto** [comment]
We decided to publish a quick write-up of the CPG on arXiv. https://arxiv.org/abs/2203.08424

More related papers are incoming and in review.
