### ISSUE TITLE
Build flag for conditional compilation of experimental features

### ISSUE THREAD

**Issue by fwendland** [Fraunhofer-AISEC/cpg#381]
The new support for Go using JNI requires the whole build chain for Go. I couldn't find a simple way to disable the experimental Go intergration during compilation. I was able to remove the compile task but there were still test cases that then failed during build/test. This is somewhat annoying if I just want to extend the Java part.

Would it be possible to add build flags to conditionally disable certain experimental features?

**Comment by oxisto** [comment]
Hmm good point. This was not the intention, I can have a look how to exclude tests and go build based on a flag.
