### ISSUE TITLE
Cleanup of duplicate ObjectType nodes

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#387]
Parsing Issue285.java (just a random file - this issue probably has nothing to do with Issue 285) with the CPG and visualizing the result yields the attached graph. This appears to be incorrect because there are multiple "Issue285" ObjectType nodes instead of a single node. Is this behavior intended? oxisto thinks this might be a bug in the cleanup pass.

![20210408_18h23m49s_grim](https://user-images.githubusercontent.com/13150274/114064274-c0fa9d00-9899-11eb-9485-1af91548bfdf.png)

**Comment by oxisto** [comment]
Good catch. This was indeed a major problem introduced in #350 and fixed now. I have also initiated a 3.4.1 hotfix release for this.
