### ISSUE TITLE
Auto-Release Strategy

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#4]
Once (in the future) we are stable enough so that we do not need to fiddle around on `master`, @titze and I discussed the following strategy:

- All development work should be done on branches and merged into master using pull requests
- The master branch will automatically release to maven central and increase its version number, i.e. `1.2.X` or `1.X`. If more functionality was added, the developer is in charge of manually bumping the version number to a major version or similar
- Optionally, also a GitHub release could be created, although it will not add too much benefit

Any thoughts on this? I am not 100 % sure yet how we can achieve the automatic versioning, but i think it should be doable.

**Comment by Masrepus** [comment]
Seems reasonable to me. I wouldn't create GitHub releases for these automatic bumps but rather only for manual releases

**Comment by vijayakumarbathini** [comment]
This can be achieved by creating a teamcity/jenkins  job for doing the development release where new release tag can be released and next version can be provided in Job configuration

**Comment by oxisto** [comment]
Closing this for now. I will do a semi-regular release every Friday if there are new features or if we really need to release a new feature or bugfix.
