### ISSUE TITLE
Refactor CallResolver to allow for more precise resolutions

### ISSUE THREAD

**Issue by vfsrfs** [Fraunhofer-AISEC/cpg#406]
The CallResolver is getting increasingly hard to maintain, since we need to distinguish between the call resolution for C++ and for Java. This will probably become worse as we want to resolve function calls of experimental languages. @konradweiss suggested to incorporate different CallResolvers based on the language with a strategy pattern, so that we can provide more precise call resolution. @konradweiss  also noted that it is probably not sufficient to check for the LanguageFrontend as we are doing currently, but instead check the language on a lower level (nodes?). The reason for this would be that there are ways to mix multiple languages, even in the same TUD. If we discuss changes in the architecture of the passes, maybe we should also take #310 into consideration.

**Comment by oxisto** [comment]
Will be addressed in #1496 by the method `bestViable` in the `Language`
