### ISSUE TITLE
Is there an example code to generate java CPG from a source file?

### ISSUE THREAD

**Issue by jz48** [Fraunhofer-AISEC/cpg#409]
Hello,

I've tried the code in readme and it works well. However, I have no idea about how to visit the cpg for a source file.

I've looked at the repo cpg-vis-neo4j, but I couldn't find an example.

Could you please tell me which api should I use to visit the cpg or is there an example to do so?

I would be very grateful if you could give me a link about this.

Best

**Comment by nhjclxc** [comment]
> 你好，
> 
> 我已经尝试了自述文件中的代码，效果很好。但是，我不知道如何访问 cpg 来获取源文件。
> 
> 我查看了 repo cpg-vis-neo4j，但找不到示例。
> 
> 你能告诉我应该使用哪个 api 来访问 cpg 或者有一个例子吗？
> 
> 如果您能给我一个有关此问题的链接，我将不胜感激。
> 
> 最好的

Please tell me how to solve your problem
