### ISSUE TITLE
CXXLanguageFrontend#getRegionFromRawNode parses region incorrect if includes are used

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#41]
To reproduce, parse any cpp file with the `loadIncludes` option on and supply the path to the include files.

It seems that it tries to parse the region by accessing the `source` field and storing it in the `parentRawSig` variable. However, this contains the source for the parent cpp source file and not the header files that are parsed as a result of it. This leads to errors and in many cases crashes since the graph nodes of the include file are looking for code/region in the source of the cpp file.

To crash, simply make the header file substantially longer than the cpp file, this way, the nodes of the header file will definitely refer to code positions that do not exist in the cpp file.

Is the alternative with using the supplied `getRawSignature` that much worse performance-wise? This function seems to be very hacky.

**Comment by konradweiss** [comment]
@JulianSchuette How costly was it and can an adaptation keep it efficient while fixing the bug?

**Comment by oxisto** [comment]
i've uploaded a (failing) test case to demonstrate the issue. please use that one to fix it https://github.com/Fraunhofer-AISEC/cpg/tree/fix-region-and-code
