### ISSUE TITLE
Cannot persist to Neo4J anymore

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#410]
It seems that #395 introduced a bug because of the conversion to a Kotlin class, so that the CPG could not persist to neo4j anymore (not sure if this also affected Codyze). Basically persisting into graph ended up in an endless recursion.

**Comment by Masrepus** [comment]
In my recent experiments I found that mixing Java and Kotlin in a reflection environment leads to very complicated behavior, where the functionality of the codyze OGM is no longer guaranteed. That's why I would strongly advise against using kotlin for any node classes

**Comment by oxisto** [comment]
It works if the base class in Kotlin. Afterwards, the extended classes can either be Java or Kotlin.

**Comment by oxisto** [comment]
It seems this problem somehow returned.
