### ISSUE TITLE
Question about typedef

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#412]
I have a question about the representation of C typedef statements in the cpg.

Example:
```C
#include <stdio.h>

typedef int MyInt;

struct  MyS {
    int a;
    int b;
    MyInt c;
};

typedef struct MyS MyS_t;


int main() {
    struct MyS s1;
    MyS_t s2;
    
    return 0;
}
```

When loading the sample C code via cpg-vis-neo4j (cpg v3.5.1), the graph looks like the following:
![cpg_graph](https://user-images.githubusercontent.com/2060591/116410308-ee04f480-a834-11eb-80a0-9c3dd536907f.png)

When analyzing structs (where typedefs are often used), it would be nice, to have an RECORD_DECLARATION edge between the ObjectType `MyS_t` and the Declaration of `MyS`. In this way the Declaration of `s1` and `s2` could be resolved the same way. 
In the current cpg, the only way I see to resolve this problem is to create a link between the VariableDeclaration `MyS_t` and the ObjectType `MyS_t` based the name.

Can you reproduce this behavior?
Is there a different way, to resolve the Declaration of `s2`?

**Comment by Masrepus** [comment]
Typedefs are generally supported, as you can see with the `TypedefDeclaration` child of the `TranslationUnitDeclaration` that maps `MyInt` to `int`. The concrete case you have here is unfortunately parsed in a wrong way by the typedef handling mechanisms

**Comment by oxisto** [comment]
<img width="304" alt="Image" src="https://github.com/user-attachments/assets/7de030d0-9b9e-4f60-8e8c-7e4406b3c107" />

Both types are resolved correctly (for a while now). Closing this issue.
