### ISSUE TITLE
Create a ThisExpression

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#43]
Currently, `this` is handled as a dummy field of a record declaration. While this works, it is not very clean in my opinion and also leads to funny errors, such as `object.this.call()` is parsed. 

We should replace it with a `ThisExpression` that refers to the record declaration and can be used as a base for member field access and calls.

**Comment by KuechA** [comment]
@oxisto has this been fixed by #835? Seems to be related

**Comment by oxisto** [comment]
> @oxisto has this been fixed by #835? Seems to be related

Yes, this can be closed.
