### ISSUE TITLE
Cannot build with -Pexperimental

### ISSUE THREAD

**Issue by jiechenjiechen** [Fraunhofer-AISEC/cpg#432]
I tried to build with the following command under bash in Mac:

`CPG_PYTHON_VIRTUALENV=py39; gradlew -Pexperimental build`

where py39 is environment where I have installed jep. My default java version is 15

```
$ java -version
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

When building, the following errors occur

```
> Task :cpg-library:test

PythonFrontendTest > testSimpleClass() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:251
        Caused by: java.lang.UnsatisfiedLinkError at ClassLoader.java:2447

PythonFrontendTest > testCtor() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:455
        Caused by: java.lang.UnsatisfiedLinkError at Jep.java:-2

PythonFrontendTest > testSelf() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:369
        Caused by: java.lang.UnsatisfiedLinkError at Jep.java:-2

PythonFrontendTest > testIf() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:207
        Caused by: java.lang.UnsatisfiedLinkError at Jep.java:-2

PythonFrontendTest > testLiteral() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:56
        Caused by: java.lang.UnsatisfiedLinkError at Jep.java:-2

PythonFrontendTest > testFunctionDeclaration() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:111
        Caused by: java.lang.UnsatisfiedLinkError at Jep.java:-2

PythonFrontendTest > testIfExpr() FAILED
    java.util.concurrent.ExecutionException at PythonFrontendTest.kt:312
        Caused by: java.lang.UnsatisfiedLinkError at Jep.java:-2

225 tests completed, 7 failed
```

I traced the errors, for example, the first one. The first line reads:

`java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no jep in java.library.path: /Users/chenjie/lab/SDG/cpg/cpg-library/src/main/golang`

I am not a go programmer and do not understand what it means. I only need the support of experimental language python and I have installed jep under the environment used for this build. Could you help me?

**Comment by oxisto** [comment]
Thanks for reaching out to us. It seems, that after some debugging together with @maximiliankaul  you / we are running into two issues here.

The `CPG_PYTHON_VIRTUALENV` is unfortunately poorly documented. It expects a virtualenv with that name in the folder `~/.virtualenvs/$CPG_PYTHON_VIRTUALENV`. Please make sure that the virtualenv is created there. Alternatively, you can explicitly specify the `CPG_JEP_LIBRARY` environment variable to the jep shared library. For example `CPG_JEP_LIBRARY=~/testmyenv/lib/python3.9/site-packages/jep/libjep.jnilib ./gradlew -Pexperimental build`

The second problem is that, currently on my Mac even if the shared library is found, the build / test fails, because jep cannot seem to the find its own python module when running in a virtualenv. Installing jep globally works. I will continue investigating, whether this is a problem with jep and raise an issue there.

**Comment by jiechenjiechen** [comment]
Thanks. I use conda to manage different environments; so if possible, would like to keep it that way. The system does not even have a `~/.virtualenvs` folder.

I installed jep globally and tried

`CPG_JEP_LIBRARY=/opt/anaconda3/envs/py39/lib/python3.9/site-packages/jep/libjep.jnilib ./gradlew -Pexperimental build`

The following error occurs:

```
> Task :cpg-library:test
INTEL MKL ERROR: dlopen(/opt/anaconda3/envs/py39/lib/libmkl_intel_thread.1.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /opt/anaconda3/envs/py39/lib/libmkl_intel_thread.1.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.1.dylib.
```

The file `libmkl_intel_thread.1.dylib` does exist; it just cannot be loaded. Is it the problem of my python 3.9 environment?

**Comment by Masrepus** [comment]
It seems like you need to install Intel MKL, try `conda install -c intel mkl`

**Comment by jiechenjiechen** [comment]
@Masrepus Intel MKL has already been installed, but the problem persists.

**Comment by jiechenjiechen** [comment]
@oxisto I confirm that using the suggested way to setup environments, I can successfully build and install.

It would be good to support also the conda way of environments, but I understand that you may have different priorities.

**Comment by jiechenjiechen** [comment]
Yet another error comes up though, when I am using cpg-neo4j:

```
$ cpg-neo4j /Users/chenjie/lab/SDG/examples/counter.py
16:26:10,057 INFO  TranslationManager Parsing /Users/chenjie/lab/SDG/examples/counter.py
16:26:10,059 ERROR TranslationManager Found no parser frontend for counter.py
```

What "parser" does it need?

**Comment by oxisto** [comment]
> Yet another error comes up though, when I am using cpg-neo4j:
> 
> ```
> $ cpg-neo4j /Users/chenjie/lab/SDG/examples/counter.py
> 16:26:10,057 INFO  TranslationManager Parsing /Users/chenjie/lab/SDG/examples/counter.py
> 16:26:10,059 ERROR TranslationManager Found no parser frontend for counter.py
> ```
> 
> What "parser" does it need?

Basically, we have different language frontends for the different languages, the word "parser" is a misnomer here, it means that no language frontend for python was found. This is expected, since `cpg-neo4j` does not yet support the experimental languages out of the box. I will try to see, if I can introduce a quick CLI flag into `cpg-neo4j` that supports them, tomorrow.

**Comment by oxisto** [comment]
@jiechenjiechen Can you have a look at this PR: https://github.com/Fraunhofer-AISEC/cpg/pull/434 please?

**Comment by jiechenjiechen** [comment]
Thanks @oxisto . The following exception occurs when I run the program from bin/cpg-neo4j

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no cpgo in java.library.path: /Users/chenjie/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
	at java.base/java.lang.System.loadLibrary(System.java:1893)
	at de.fraunhofer.aisec.cpg.frontends.golang.GoLanguageFrontend.<clinit>(GoLanguageFrontend.kt:45)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.setupTranslationConfiguration(Application.kt:251)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:289)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:71)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:321)
```

Note that I have specified java.home when building the library 

`gradlew -Dorg.gradle.java.home="/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home" build`

**Comment by oxisto** [comment]
> Thanks @oxisto . The following exception occurs when I run the program from bin/cpg-neo4j following #434
> 
> ```
> Exception in thread "main" java.lang.UnsatisfiedLinkError: no cpgo in java.library.path: /Users/chenjie/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
> 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
> 	at java.base/java.lang.System.loadLibrary(System.java:1893)
> 	at de.fraunhofer.aisec.cpg.frontends.golang.GoLanguageFrontend.<clinit>(GoLanguageFrontend.kt:45)
> 	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.setupTranslationConfiguration(Application.kt:251)
> 	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:289)
> 	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:71)
> 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
> 	at picocli.CommandLine.access$1300(CommandLine.java:145)
> 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
> 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
> 	at picocli.CommandLine.execute(CommandLine.java:2078)
> 	at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:321)
> ```
> 
> Note that I have specified java.home when building the library
> 
> `gradlew -Dorg.gradle.java.home="/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home" build`

Ah, now this problems occurs because it will also include the Go implementation. I will split the flag into two. one for python and one for Go.

**Comment by oxisto** [comment]
@jiechenjiechen did you have a chance to test the updated PR? I have split the flags into specific ones for python and go

**Comment by jiechenjiechen** [comment]
@oxisto I confirm that `--enable-experimental-python` works. I guess the implementation is incomplete, but at least it generates a graph.

```
$ bin/cpg-neo4j --enable-experimental-python /Users/chenjie/lab/SDG/examples/counter.py
10:32:18,870 INFO  TranslationManager Parsing /Users/chenjie/lab/SDG/examples/counter.py
10:32:19,066 ERROR Jep visit_ClassDef	1182:	This is not (yet) implemented.
10:32:19,321 WARN  TypeManager No frontend available. Be aware that typedef resolving cannot currently be done
10:32:19,324 ERROR Jep visit_ClassDef	1182:	This is not (yet) implemented.
```

Thank you for the efforts!

**Comment by maximiliankaul** [comment]
Hi @jiechenjiechen 
can you provide your test file (counter.py)? Python support is work in progress and I am currently adding features as needed.
Thanks

**Comment by jiechenjiechen** [comment]
Here is the code. I does not look like what people normally have; we purposely write this obscure code in a research project. Hope it would be helpful for your development.

```
$ cat counter.py 
class counter:
    pass

def count(c):
  if c.inc() < 5:
    count(c)

class c1(counter):
  total = 0

  def inc(self):
    self.total = self.total + 1
    return self.total

count(c1())
```

**Comment by oxisto** [comment]
Closing this for now, since it seems sort of resolved. Thank you for the example. Something like this would make a good test case for the Python parser.
