### ISSUE TITLE
Different frontends are used for multiple files. This will very likely break the following passes.

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#448]
@konradweiss, I get a lot of those errors in a multi-language scenario. Can we safely remove the error message? Not sure, why it is there in the first place.

https://github.com/Fraunhofer-AISEC/cpg/blob/a3eda2fe3487f34837b76c739f07872e1c0c525d/cpg-library/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java#L223

**Comment by Masrepus** [comment]
I'm not sure call and variable resolution would work properly in such a scenario...

**Comment by konradweiss** [comment]
We can remove this warning, it should currently work properly.
