### ISSUE TITLE
Unexpected C function call representation if function called `new`

### ISSUE THREAD

**Issue by fwendland** [Fraunhofer-AISEC/cpg#449]
I have the following C code:
```c
#include <stdlib.h>

struct s {
    int a;
};

typedef struct s S;


S* new() {
    return malloc(sizeof(S));
}

void fun() {
    S *sptr = new();
}
```

I've used the Neo4j tool to get an idea to get an idea how the code looks:
![def-c-neo4j](https://user-images.githubusercontent.com/11220054/123657051-be706980-d830-11eb-8cd2-cb3195863a62.png)

The large node is a `CallExpression`. It should represent the function call to `new()`. 

What is surprising is:
- function call is in the function `fun()`. Why isn't the node part of the EOG of `fun`?
- the function code contains as code only `()`. What happened to its name?

**Comment by fwendland** [comment]
The problem goes away, when the function isn't called `new()` if that helps. However, `new()` is a valid C function name without special meaning afaik.

![def-c-ne04j-notnew](https://user-images.githubusercontent.com/11220054/123661044-7fdcae00-d834-11eb-80bc-a62e9ffe9c6a.png)

**Comment by oxisto** [comment]
This is/was fixed. The code is `code` is `new()` and the EOG is also connected. I suspect that we are handling the differences between C and C++ better now.
