### ISSUE TITLE
Store Record bodies / TranslationUnit bodies in the graph

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#464]
Currently, we cannot handle code like the following python snippet:
```Python
print("HELLO")
class Foo:
  print("WORLD")
```
Neither of the two print statements can be stored in CPG as the RecordDeclaration, NamespaceDeclaration, TranslationUnitDeclaration do not supports a `body` (or similar) container.
This issue is likely relevant for other scripting languages besides python, too.

**Comment by oxisto** [comment]
I am also running into this issue with TypeScript - or any other script-based language for that matter. I will try to set up a call next week once every one is back in office.
