### ISSUE TITLE
Wrong Base-Reference for Static calls

### ISSUE THREAD

**Issue by titze** [Fraunhofer-AISEC/cpg#5]
for 
```java
private static byte[] setMasterPass(String mastPass, byte[] salt) throws IOException, NoSuchAlgorithmException {
        //Create new hash with SHA512
        MessageDigest md = MessageDigest.getInstance("SHA-512");
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        bout.write(salt);
        bout.write(mastPass.getBytes());
        return md.digest(bout.toByteArray());
    }
```
(MessageDigest.getInstance is a static Call)

the `base` of `getInstance` should not be `this`!

**Comment by Masrepus** [comment]
Seems to have a deeper underlying issue that prevents static calls from being resolved correctly

**Comment by titze** [comment]
The issue can be that if `MessageDigest` is not available, the Parser might think it is a variable. But it should not be `this`?

**Comment by Masrepus** [comment]
@titze Now it should work as expected. I'll create some general call resolver tests once I get the performance benchmark up and running
