### ISSUE TITLE
Remove NodeBuilder implicit "this" field

### ISSUE THREAD

**Issue by maximiliankaul** [Fraunhofer-AISEC/cpg#511]
Remove the implicit `this` field in the NodeBuilder's `newRecordDeclaration`

### Discussed in https://github.com/Fraunhofer-AISEC/cpg/discussions/510

<div type='discussions-op-text'>

<sup>Originally posted by **maximiliankaul** August 12, 2021</sup>
https://github.com/Fraunhofer-AISEC/cpg/blob/f065ed684301cf8fcb436fcf0faad397f5bf27b1/cpg-library/src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java#L449

The NodeBuilder's `newRecordDeclaration` always names the receiver `this`. However, python's convention (not enforced) is to name the receiver `self`. Should this be configurable?</div>

**Comment by oxisto** [comment]
Has been fixed by #835
