### ISSUE TITLE
MemberExpression references a wrongly created field

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#52]
The sample "InstanceShenanagans" shows how the Base edge points to a field of the class. This field is not part of the original class and has type and name of the used variable name. This is definitly wrong. 
The Base currently seams to reference manydifferent things, e.g. RecordDeclarations, Fields etc.. 
IMO they should only reference the variable used for the access over a DeclaredReferenceExpression. 
For now i will investigate this problem and remove this wrongly added field. A PR will be used for the fix and for further changes if we decide to limit the node types that can be pointed to by the base.
![instance_shenenagans](https://user-images.githubusercontent.com/12885000/73537586-1f6ff400-4429-11ea-800e-9766c8a42b9a.png)

[InstanceShenenegans.zip](https://github.com/Fraunhofer-AISEC/cpg/files/4139149/InstanceShenenegans.zip)

**Comment by oxisto** [comment]
If you are at it, please also have a look at #43
