### ISSUE TITLE
Scope Manager is needed for all passes

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#55]
Frontends are now created per file and therefore the contained ScopeManager is always recreated. Because in the end only one language-frontend is set to all passes after the frontend-run, the Scope Manager must be independent from the frontends. Scopes are created and can then be reused in later passes, but between different analysis runs the ScopeManager must be different (No Singleton).
This allows for passes to enter scopes and their parent scopes, without having to traverse the AST in the right order but randomly access scopes.
This is done in the process to fix #52 and reenable the VariableUsageResolver to work with the ScopeManager.
NOTE: If we allow different filetypes in one analysis (.java, .cpp) we should also change the way Frontends are given to passes, either we create a frontend per file, or they are the same for files of the same language, only one Frontend per supported Language.

**Comment by konradweiss** [comment]
The random access may not work (currently) at nodes that do not declare their own scope, e.g. A Statement **s** in a CompoundStatement **cs**. enter(s) does not work, while enter(cs) does.

**Comment by oxisto** [comment]
Was this fixed by #56?

**Comment by konradweiss** [comment]
Yes. At a later point, we will have to look at the language frontends that are passed to the passes. Currently, they seem to get the last frontend created, which will be a problem as soon as we analyze several files that use a different frontend:
`
      // Set frontend so passes know what language they are working on.
      for (Pass pass : config.getRegisteredPasses()) {
        pass.setLang(frontend);
      }
` 
I will create a new Issue for that one though.
