### ISSUE TITLE
Can I config handler for JavaLanguageFrontEnd?

### ISSUE THREAD

**Issue by pangeneral** [Fraunhofer-AISEC/cpg#555]
Hello, I'm using JavaLanguageFrontend and I found that modifiers of classes are discarded during `handleJavaClassOrInterfaceDeclaration`. Besides, if there is `EnumDeclaration` inside a class, the enum is also discarded. 

Now I want to rewrite `handleJavaClassOrInterfaceDeclaration` and change `declarationHandler` of JavaLanguageFrontend. However, `declarationHandler` is private and there isn't setter method. I'm wondering how I can cope with the problem.

**Comment by oxisto** [comment]
Hi! Discarding the modifiers is not intentionally, we just had not the time yet to implement this. If you have any interest in implementing this, we would be very interested, unfortunately we have not yet set up all the processes for external contributions through CLAs etc., so it might take a while for us to accept it into the main branch.

In the meantime, if it helps, we could set `declarationHandler` to `protected` so that you can extend the `JavaLanguageFrontend` with your own extended implementation

**Comment by pangeneral** [comment]
> Hi! Discarding the modifiers is not intentional, we just had not the time yet to implement this. If you have any interest in implementing this, we would be very interested, unfortunately we have not yet set up all the processes for external contributions through CLAs etc., so it might take a while for us to accept it into the main branch.
> 
> In the meantime, if it helps, we could set `declarationHandler` to `protected` so that you can extend the `JavaLanguageFrontend` with your own extended implementation

I tried to defined a subclass of `DeclarationHandler` and set `declarationHandler` via Reflection. However, my self-defined subclass isn't `ParameterizedType` and `ClassCastException` is throwed when the following code is invoked ` (Class<S>)   ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[1];` to init `typeOfT` of `Handler`. It seems that we can't set `declarationHandler`  since the existence of `typeOfT` even `declarationHandler` is `protected`.

**Comment by oxisto** [comment]
> > Hi! Discarding the modifiers is not intentional, we just had not the time yet to implement this. If you have any interest in implementing this, we would be very interested, unfortunately we have not yet set up all the processes for external contributions through CLAs etc., so it might take a while for us to accept it into the main branch.
> > In the meantime, if it helps, we could set `declarationHandler` to `protected` so that you can extend the `JavaLanguageFrontend` with your own extended implementation
> 
> I tried to defined a subclass of `DeclarationHandler` and set `declarationHandler` via Reflection. However, my self-defined subclass isn't `ParameterizedType` and `ClassCastException` is throwed when the following code is invoked ` (Class<S>) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[1];` to init `typeOfT` of `Handler`. It seems that we can't set `declarationHandler` since the existence of `typeOfT` even `declarationHandler` is `protected`.

I have addressed this particular issue in #672 although I want to make it a bit more robust.
