### ISSUE TITLE
Utility helper function to create consistent language frontends for unit tests

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#57]
Just a suggestion: @konradweiss: Would it make sense to have an (abstract) test class somewhere and define a utility function like `newLanguageFrontend` for unit tests that ensure that all the tests (at least the ones without the pass invocations) have a consistent creation-pattern for the language frontend?, i.e.

- The desired language frontend class
- A "dummy" translation manager configuration
- Path to the correct file (as argument)
- a new `ScopeManger`

This function could then be used to document that this will NOT run the passes. Otherwise we have 20+ tests that need to be adjusted and this way it is only 1 function.

_Originally posted by @oxisto in https://github.com/Fraunhofer-AISEC/cpg/pull/56#issuecomment-581361387_

**Comment by oxisto** [comment]
@Masrepus Is this obsolete and fixed by #117 ?

**Comment by Masrepus** [comment]
No, not yet. This is fixed as part of my general testing overhaul in #116, but it's not merged yet. I guess that this will take some more time, but we can merge it in several subsequent PRs, as #116 consists of rather independent fixes.
