### ISSUE TITLE
using typescript in cpg-neo4j

### ISSUE THREAD

**Issue by anisyusof-sc** [Fraunhofer-AISEC/cpg#574]
hi all. may i know if it possible to add support for TypeScript (and its variants *.js, *.jsx etc.) in cpg-neo4j? appreciate if it can be something like `--enable-experimental-typescript` , similar to both Python and Go.

**Comment by oxisto** [comment]
Good idea. That should be relatively easy to do.

**Comment by anisyusof-sc** [comment]
hey @oxisto , thank you very much for the quick response and fixes that you've made. I can confirm that cpg-neo4j is working well with `--enable-experimental-typescript` after building with `-PexperimentalTypeScript` based on the separate branch. 

thanks to you & to all the devs for maintaining this project!
