### ISSUE TITLE
Passes get the last LanguageFrontend that was created.

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#59]
`
      // Set frontend so passes know what language they are working on.
      for (Pass pass : config.getRegisteredPasses()) {
        pass.setLang(frontend);
      }
`
This is executed at the end of `runFrontends` with frontend being set in the loop that executes the frontends on the files. Therefore only the last frontend is set to all passes.
This can stay as long as frontends are static in relation to the processed files (no TranslationUnit dependent state is internally stored), but will have to change as soon as we allow the analysis of code that uses different Frontends.

**Comment by konradweiss** [comment]
Frontend creation inside loop: https://github.com/Fraunhofer-AISEC/cpg/blob/1057e88681477b05fa2ca0ead63df98dfe70e7af/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java#L172-L174
Passes getting the Frontend: https://github.com/Fraunhofer-AISEC/cpg/blob/1057e88681477b05fa2ca0ead63df98dfe70e7af/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.java#L215-L217

**Comment by JulianSchuette** [comment]
Yes, this is known, see #53 IMHO, it currently is a case of YAGNI - passes are not ready to handle cross-language analyses anyway. Can stay as it is.
Later, passes might receive the `sfToFe` map.

**Comment by konradweiss** [comment]
Passes are working on nodes only right? Or do they have access to the SourceFile of a Node? If they don't then mapping of Nodes to Frontend will be more complicated. It is not essential I guess. If we ever want to create a joined Graph of Java and CPP code, e.g. Android App code and Native CPP code, we may do two passes and some graph merging approach. Only if the pass itself has to work across Languages there may be a problem ( Calls are the only case that currently comes to my mind)

**Comment by Masrepus** [comment]
#99 is the first case where a pass had to specifically know which language we are dealing with, as "super" is a keyword in Java that has a special meaning, while you can name your C variables "super" as long as you like
