### ISSUE TITLE
AST leaves containing all "default" statements in switch case instructions

### ISSUE THREAD

**Issue by NiccoloTogni** [Fraunhofer-AISEC/cpg#605]
Hi!

We are trying to extract CPGs from Java code snippets.
We observe that whenever the code contains switch case instructions, all the default statements (if there are multiple) are contained in a node labeled "Node.Statement.DefaultStatement" which is an AST leaf. We were expecting AST leaves to only contain singular code tokens or strings hence why we are reporting the issue.

For more context, here is an example of a snippet of code from which we extracted the CPG:

```
public class file_10793 {
public void testMethod(HttpServletRequest request, HttpServletResponse response) throws Throwable
    {
        String data = null;

        switch (5)
        {
        case 6:
            
            data = null;
            break;
        default:
            
            data = "foo";
            break;
        }

        /*(...)*/

    }
```

and here is the code contained in the DefaultStatementNode (which is an AST leaf):

```
default:
            
            data = "foo";
            break;
```

**Comment by copernico** [comment]
Hi @oxisto, @konradweiss , any news on this issue?

**Comment by konradweiss** [comment]
@copernico @NiccoloTogni Sorry for answering with such a delay. In Java the parser does not put the case and default statements on the same level. Instead the case contains its statements. In the CPG we model all case-, default and code statements on the same hierarchy level to make it consistent with other languages. The "Code" property is taken from the original Java node, and therefor the text contains the substatements as well. 

Now this could be argued to be fine, if you want the nodes to represent the actual locations in the original source code. However, if you expect the code-property to match the CPG-AST structure there is an obvious problem. This could be changed but has some implications on how the code field is set and what it means.
