### ISSUE TITLE
CallExpression is connected to wrong MethodDeclaration

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#650]
In case the implementation of a method is not given, but a method with same name and same signature (but from a different class) exists, the `CallExpression` is connected to the wrong `MethodDeclaration` (via `INVOKES` edge).

Example:
```c++
class A {
public:
        void foo(int a);
};

class B {
public:
        void foo(int a);
};

void B::foo(int a) {
}

int main() {
        A a;
        B b;

        a.foo(1);
        b.foo(2);

        foo();

        C c;
        c.foo(3);
}
```

When loading the example c++ code into the cpg, all three calls of a method `foo` (`a.foo`, `b.foo`, `c.foo`) are connected to the `MethodDeclaration` of `B::foo`.

![cpg_bug_CallExpression](https://user-images.githubusercontent.com/2060591/148218285-15f4b7b8-8b48-4854-97b9-c80da9d703d2.png)

**Comment by oxisto** [comment]
Yeah, it seems like this is completely broken :( Maybe it's finally time for a rewrite of the CallResolver :(
