### ISSUE TITLE
Analysis of particular C file not finishing in time

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#658]
> I meant the snippet for the source code file that seems to crash the analysis :) A time limit per file is indeed something that we do not have :( If the analysis does not finish in adequate time it seems to hint to another error.

This file for example is not finishing in reasonable time whatsoever: [ianatables.c](https://github.com/GNOME/libxml2/blob/master/os400/iconv/ianatables.c ). It's not super important for me that this file gets parsed, since it yields little information of interest, however, the entire parsing should terminate at least. :D 

> If you are using C/C++, you might also benefit from the unity builds (without parallel), since they combine all the code into a single translation unit, removing double header includes, etc.

I tried unity builds, but it's not working for me. The graphs are just empty :( ( using those snippets https://gist.github.com/anon767/d47295dae6c3e63b157655c708c7585e )

Another more or less related question:
Is there a way to merge translationUnitDeclarations from different analysis passes? E.g. each file is analyzed and parsed separately (like in the example from my last post) and then merged into a single TranslationResult? 
Then it would be possible to run a CallResolver pass over the merged translationDeclarations. When I tried that, I wasn't too sure how to populate the Scopes correctly.

Edit://
I think the unity build problem is my fault. I'm reading the files without specifying topLevel in the configuration. I guess that's the issue here right?

_Originally posted by @anon767 in https://github.com/Fraunhofer-AISEC/cpg/discussions/655#discussioncomment-1939435_

**Comment by oxisto** [comment]
It seems to be stuck on activating types (when using the parallel frontend), which seems completely unnecessary, since the file only contains of (a lot) of literals, whose type will not change at all. 

```
12:53:22,989 INFO  Benchmark TranslationManager: Translation into full graph
12:53:22,993 INFO  Benchmark TranslationManager: Frontend
12:53:22,999 INFO  TranslationManager Parallel parsing started
12:53:23,131 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile
12:53:23,694 INFO  CXXLanguageFrontend Parsed 352243 bytes corresponding roughly to 7044 LoC
12:53:23,694 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile done in 562 ms
12:53:23,694 INFO  Benchmark CXXLanguageFrontend: Transform to CPG
12:53:58,755 INFO  Benchmark CXXLanguageFrontend: Transform to CPG done in 35060 ms
12:53:58,761 INFO  TranslationManager Parallel parsing completed
12:53:58,761 DEBUG Benchmark TranslationManager: Activating types for /Users/chr55316/Repositories/cpg/cpg-core/src/test/resources/ianatables.c
(currently stuck)
```

**Comment by oxisto** [comment]
This seems to be related to a weird type listener in the initialiser list:

https://github.com/Fraunhofer-AISEC/cpg/blob/c4e6a33f2e076906e7412a8127e817ba3e16b7ff/cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/InitializerListExpression.java#L92-L110

Basically, it will iterator the whole list again. @konradweiss Do you have any idea why this there?

**Comment by oxisto** [comment]
@anon767 can you give https://github.com/Fraunhofer-AISEC/cpg/pull/661 a spin? I have tested it internally with the IANA file and these are my results (MacBook Pro M1):

```
19:07:19,521 INFO  Benchmark TranslationManager: Translation into full graph
19:07:19,524 INFO  Benchmark TranslationManager: Frontend
19:07:19,530 INFO  TranslationManager Parsing /Users/chr55316/Repositories/cpg/cpg-core/src/test/resources/ianatables.c
19:07:19,653 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile
19:07:20,235 INFO  CXXLanguageFrontend Parsed 352243 bytes corresponding roughly to 7044 LoC
19:07:20,236 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile done in 582 ms
19:07:20,236 INFO  Benchmark CXXLanguageFrontend: Transform to CPG
19:07:21,673 INFO  Benchmark CXXLanguageFrontend: Transform to CPG done in 1436 ms
19:07:21,675 INFO  Benchmark TranslationManager: Frontend done in 2150 ms
19:07:21,675 INFO  Benchmark TypeHierarchyResolver: Executing Pass
19:07:21,976 INFO  Benchmark TypeHierarchyResolver: Executing Pass done in 300 ms
19:07:21,976 INFO  Benchmark JavaExternalTypeHierarchyResolver: Executing Pass
19:07:21,976 INFO  Benchmark JavaExternalTypeHierarchyResolver: Executing Pass done in 0 ms
19:07:21,976 INFO  Benchmark ImportResolver: Executing Pass
19:07:22,013 INFO  Benchmark ImportResolver: Executing Pass done in 36 ms
19:07:22,013 INFO  Benchmark VariableUsageResolver: Executing Pass
19:07:25,381 INFO  Benchmark VariableUsageResolver: Executing Pass done in 3368 ms
19:07:25,381 INFO  Benchmark CallResolver: Executing Pass
19:07:28,658 INFO  Benchmark CallResolver: Executing Pass done in 3276 ms
19:07:28,658 INFO  Benchmark EvaluationOrderGraphPass: Executing Pass
19:07:30,531 INFO  Benchmark EvaluationOrderGraphPass: Executing Pass done in 1872 ms
19:07:30,531 INFO  Benchmark TypeResolver: Executing Pass
19:07:31,573 INFO  Benchmark TypeResolver: Executing Pass done in 1041 ms
19:07:31,573 INFO  Benchmark ControlFlowSensitiveDFGPass: Executing Pass
19:07:32,576 INFO  Benchmark ControlFlowSensitiveDFGPass: Executing Pass done in 1002 ms
19:07:32,576 INFO  Benchmark FilenameMapper: Executing Pass
19:07:32,604 INFO  Benchmark FilenameMapper: Executing Pass done in 27 ms
19:07:32,604 INFO  Benchmark TranslationManager: Translation into full graph done in 13088 ms
19:07:32,613 INFO  Benchmark IanaTest: getAstChildren
19:07:32,668 INFO  Benchmark IanaTest: getAstChildren done in 54 ms
BUILD SUCCESSFUL in 18s
```

I would say that is some performance improvement ;)

**Comment by anon767** [comment]
Thanks! Works like a charm :)
