### ISSUE TITLE
C++ methods defined inside a class are not handled correctly

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#674]
Methods defined inside a class are not handled correctly. 

Example:
```c++
class T {
public:
        T(int i);
        void foo()
        {
                std::cout << "T::foo()" << std::endl;
        }
        void bar();
};

T::T(int i) {
        std::cout << "T::T: " << i << std::endl;
}
void T::bar() {
        std::cout << "T::bar()" << std::endl;
}

int main() {
        T t(1);
        t.foo();
        t.bar();

        return 0;
}
```

![cpg_bug_incline_method](https://user-images.githubusercontent.com/2060591/149322514-7378bf9d-351f-455a-9a73-2620ec56dc8d.png)

**Comment by oxisto** [comment]
And the issue is that `foo` missing a body? do you have all edges extended? So far, I see nothing wrong with this picture here.

**Comment by oxisto** [comment]
<img width="828" alt="Screenshot 2022-01-13 at 16 18 37" src="https://user-images.githubusercontent.com/12459061/149357407-a62158d7-5ec4-4978-bff3-e02d3a3981ec.png">

The in-memory representation seems fine.

**Comment by peckto** [comment]
Thanks for the hint.
It was my mistake. I used the neo4j import option `--save-depth 3` to limit the recursion depth, which is the reason that not the whole graph was loaded into neo4j. Without this option, the graph is fine.

I didn't expect that option to have an influence on this small example. I thought, the depth option only limits walking edges to non-AST nodes, as these nodes are not passed to the neo4j import function.
In my understanding, the necessary nodes in this example should be part of the AST, so the depth option should have no influence. But maybe my understanding is wrong.

In any case, this issue is not a bug, sorry for blaming you for my own mistake ^^
