### ISSUE TITLE
Parsing takes long for FFmpeg

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#675]
Hi,
Im currently trying to analyse several commits of the FFmpeg Project. 
Here are some files where the parsing takes longer than 5 minutes:

https://github.com/FFmpeg/FFmpeg/blob/a32dbf2aed3bb720a28141e1e84284ade3969a49/libavcodec/hqxvlc.c
https://github.com/FFmpeg/FFmpeg/blob/a32dbf2aed3bb720a28141e1e84284ade3969a49/libavcodec/dcadata.c
https://github.com/FFmpeg/FFmpeg/blob/a32dbf2aed3bb720a28141e1e84284ade3969a49/libavcodec/on2avcdata.c
https://github.com/FFmpeg/FFmpeg/blob/a32dbf2aed3bb720a28141e1e84284ade3969a49/libavcodec/hq_hqadata.c

Those files mostly consist of large constant array declarations. These look kind of related to this:
https://github.com/Fraunhofer-AISEC/cpg/issues/658

Im currently using:
```
    api("com.github.Fraunhofer-AISEC.cpg:cpg-core:master-SNAPSHOT")
```

For some reasons even those files take very long, for which I don't see any particular reason.

https://github.com/FFmpeg/FFmpeg/blob/a32dbf2aed3bb720a28141e1e84284ade3969a49/libavcodec/proresdata.c
https://github.com/FFmpeg/FFmpeg/blob/a32dbf2aed3bb720a28141e1e84284ade3969a49/libavcodec/v210dec.c

Thanks in advance and regards

**Comment by oxisto** [comment]
hqxvlc.c seems ok for me:

13:25:53,482 INFO  Benchmark TranslationManager: Translation into full graph
13:25:53,485 INFO  Benchmark TranslationManager: Frontend
13:25:53,490 INFO  TranslationManager Parallel parsing started
13:25:53,648 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile
13:25:53,872 DEBUG CXXLanguageFrontend$includeFileContentProvider$1 Include file not found: /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqx.h
13:25:53,872 DEBUG CXXLanguageFrontend$includeFileContentProvider$1 Include file not found: /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqx.h
13:25:54,756 INFO  CXXLanguageFrontend Parsed 343320 bytes corresponding roughly to 6866 LoC
13:25:54,756 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile done in 1107 ms
13:25:54,756 INFO  Benchmark CXXLanguageFrontend: Transform to CPG
13:25:57,669 INFO  Benchmark CXXLanguageFrontend: Transform to CPG done in 2912 ms
13:25:57,673 INFO  TranslationManager Parallel parsing completed
13:25:57,673 DEBUG Benchmark TranslationManager: Activating types for /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c
13:25:59,806 DEBUG SubgraphWalker Activated 21953 nodes for /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c
13:26:00,104 DEBUG Benchmark TranslationManager: Activating types for /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c done in 2431 ms
13:26:00,105 INFO  Benchmark TranslationManager: Frontend done in 6619 ms
13:26:00,105 INFO  Benchmark TypeHierarchyResolver: Executing Pass
13:26:01,666 INFO  Benchmark TypeHierarchyResolver: Executing Pass done in 1561 ms
13:26:01,666 INFO  Benchmark JavaExternalTypeHierarchyResolver: Executing Pass
13:26:01,667 INFO  Benchmark JavaExternalTypeHierarchyResolver: Executing Pass done in 0 ms
13:26:01,667 INFO  Benchmark ImportResolver: Executing Pass
13:26:02,376 INFO  Benchmark ImportResolver: Executing Pass done in 709 ms
13:26:02,376 INFO  Benchmark VariableUsageResolver: Executing Pass
13:26:06,018 WARN  Util /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c:2158:5: Did not find a declaration for HQX_DC_VLC_BITS
13:26:06,019 WARN  Util /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c:2159:5: Did not find a declaration for HQX_DC_VLC_BITS
13:26:06,019 WARN  Util /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c:2160:5: Did not find a declaration for HQX_DC_VLC_BITS
13:26:07,379 INFO  Benchmark VariableUsageResolver: Executing Pass done in 5002 ms
13:26:07,379 INFO  Benchmark CallResolver: Executing Pass
13:26:12,694 INFO  Benchmark CallResolver: Executing Pass done in 5314 ms
13:26:12,695 INFO  Benchmark EvaluationOrderGraphPass: Executing Pass
13:26:14,454 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.ProblemDeclaration is not supported (yet)
13:26:16,022 INFO  Benchmark EvaluationOrderGraphPass: Executing Pass done in 3327 ms
13:26:16,023 INFO  Benchmark TypeResolver: Executing Pass
13:26:17,794 INFO  Benchmark TypeResolver: Executing Pass done in 1771 ms
13:26:17,794 INFO  Benchmark ControlFlowSensitiveDFGPass: Executing Pass
13:26:19,486 INFO  Benchmark ControlFlowSensitiveDFGPass: Executing Pass done in 1691 ms
13:26:19,486 INFO  Benchmark FilenameMapper: Executing Pass
13:26:20,196 INFO  Benchmark FilenameMapper: Executing Pass done in 709 ms
13:26:20,196 INFO  Benchmark TranslationManager: Translation into full graph done in 26718 ms
Disconnected from the target VM, address: 'localhost:51526', transport: 'socket'
BUILD SUCCESSFUL in 57s
20 actionable tasks: 20 executed
13:26:24: Task execution finished ':cpg-core:test --tests "de.fraunhofer.aisec.cpg.frontends.cpp.CXXLanguageFrontendTest.testFF"'.
I am parsing it without the includes, though.

**Comment by oxisto** [comment]
> hqxvlc.c seems ok for me:
> 
> ```
> 13:25:53,482 INFO  Benchmark TranslationManager: Translation into full graph
> 13:25:53,485 INFO  Benchmark TranslationManager: Frontend
> 13:25:53,490 INFO  TranslationManager Parallel parsing started
> 13:25:53,648 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile
> 13:25:53,872 DEBUG CXXLanguageFrontend$includeFileContentProvider$1 Include file not found: /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqx.h
> 13:25:53,872 DEBUG CXXLanguageFrontend$includeFileContentProvider$1 Include file not found: /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqx.h
> 13:25:54,756 INFO  CXXLanguageFrontend Parsed 343320 bytes corresponding roughly to 6866 LoC
> 13:25:54,756 INFO  Benchmark CXXLanguageFrontend: Parsing sourcefile done in 1107 ms
> 13:25:54,756 INFO  Benchmark CXXLanguageFrontend: Transform to CPG
> 13:25:57,669 INFO  Benchmark CXXLanguageFrontend: Transform to CPG done in 2912 ms
> 13:25:57,673 INFO  TranslationManager Parallel parsing completed
> 13:25:57,673 DEBUG Benchmark TranslationManager: Activating types for /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c
> 13:25:59,806 DEBUG SubgraphWalker Activated 21953 nodes for /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c
> 13:26:00,104 DEBUG Benchmark TranslationManager: Activating types for /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c done in 2431 ms
> 13:26:00,105 INFO  Benchmark TranslationManager: Frontend done in 6619 ms
> 13:26:00,105 INFO  Benchmark TypeHierarchyResolver: Executing Pass
> 13:26:01,666 INFO  Benchmark TypeHierarchyResolver: Executing Pass done in 1561 ms
> 13:26:01,666 INFO  Benchmark JavaExternalTypeHierarchyResolver: Executing Pass
> 13:26:01,667 INFO  Benchmark JavaExternalTypeHierarchyResolver: Executing Pass done in 0 ms
> 13:26:01,667 INFO  Benchmark ImportResolver: Executing Pass
> 13:26:02,376 INFO  Benchmark ImportResolver: Executing Pass done in 709 ms
> 13:26:02,376 INFO  Benchmark VariableUsageResolver: Executing Pass
> 13:26:06,018 WARN  Util /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c:2158:5: Did not find a declaration for HQX_DC_VLC_BITS
> 13:26:06,019 WARN  Util /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c:2159:5: Did not find a declaration for HQX_DC_VLC_BITS
> 13:26:06,019 WARN  Util /Users/oxisto/Repositories/cpg/cpg-core/src/test/resources/hqxvlc.c:2160:5: Did not find a declaration for HQX_DC_VLC_BITS
> 13:26:07,379 INFO  Benchmark VariableUsageResolver: Executing Pass done in 5002 ms
> 13:26:07,379 INFO  Benchmark CallResolver: Executing Pass
> 13:26:12,694 INFO  Benchmark CallResolver: Executing Pass done in 5314 ms
> 13:26:12,695 INFO  Benchmark EvaluationOrderGraphPass: Executing Pass
> 13:26:14,454 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.ProblemDeclaration is not supported (yet)
> 13:26:16,022 INFO  Benchmark EvaluationOrderGraphPass: Executing Pass done in 3327 ms
> 13:26:16,023 INFO  Benchmark TypeResolver: Executing Pass
> 13:26:17,794 INFO  Benchmark TypeResolver: Executing Pass done in 1771 ms
> 13:26:17,794 INFO  Benchmark ControlFlowSensitiveDFGPass: Executing Pass
> 13:26:19,486 INFO  Benchmark ControlFlowSensitiveDFGPass: Executing Pass done in 1691 ms
> 13:26:19,486 INFO  Benchmark FilenameMapper: Executing Pass
> 13:26:20,196 INFO  Benchmark FilenameMapper: Executing Pass done in 709 ms
> 13:26:20,196 INFO  Benchmark TranslationManager: Translation into full graph done in 26718 ms
> Disconnected from the target VM, address: 'localhost:51526', transport: 'socket'
> BUILD SUCCESSFUL in 57s
> 20 actionable tasks: 20 executed
> 13:26:24: Task execution finished ':cpg-core:test --tests "de.fraunhofer.aisec.cpg.frontends.cpp.CXXLanguageFrontendTest.testFF"'.
> ```
> 
> I am parsing it without the includes, though.

Parsing it with headers is even slightly faster. What kind of machine are you using? My benchmarks are coming from a MacBook M1. I do already have an idea though how to improve speed even more.

**Comment by anon767** [comment]
> > hqxvlc.c seems ok for me:
> Parsing it with headers is even slightly faster. What kind of machine are you using? My benchmarks are coming from a MacBook M1. I do already have an idea though how to improve speed even more.

Okay thanks for cross-checking. Im using following configuration, parsing one file after another
```
    val translationConfiguration = TranslationConfiguration.builder()
                .sourceLocations(filePath)
                .defaultPasses()
                .defaultLanguages()
                .processAnnotations(true)
                .codeInNodes(true)
                .debugParser(false)
                .failOnError(false)
                .symbols(symbols)
                .useParallelFrontends(true)
                .typeSystemActiveInFrontend(false)
                .registerPass(IdentifierPass())
```

let me quick check if the problem could be the symbols I pass in or my custom IdentifierPass

**Comment by anon767** [comment]
Hm the problem still occurs to me. However its working fine on my MacBook Pro 2019 haha. Strange

**Comment by anon767** [comment]
Well increasing the JVMs max stack size solved the issue. I have different Java versions running on the machines, I suspect that there is a minor difference causing the performance discrepancies.
Thanks though :)
