### ISSUE TITLE
Introduce `callee` property on a `CallExpression`

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#689]
In languages with function points, we could have functions as part of a struct, which will verry mutch look like a `MemberCallExpression` but which is still a `CallExpression`

Example:
```c++
struct A {
        void foo(int i) {
        }
};

struct B {
        void (*bar)(int);
};

void bar(int i) {
}

int main() {
        A a;
        a.j = 1;
        B b;
        b.bar = &bar;

        // foo is a method
        (a.foo)(1); 
        a.foo(2); 

        // bar is a function pointer
        (b.bar)(3);
        (*b.bar)(4);

        return 0;
}
```

Because the `CallExpression` has no `member` property, we cannot reflect this expression in the current graph layout.
As discussed in #682, a clean solution would be to add a `callee` property to the `CallExpression` and maybe get rid of the `base` property of the `MemberCallExpression`.

The new property could look like the following:
![callee-property](https://user-images.githubusercontent.com/2060591/151348935-f302c913-7d21-4534-b353-5b6a8de51105.png)

In this issue we can discuss this change in the graph layout and possible implications.

**Comment by oxisto** [comment]
Related to #298. Ideally, our solution would get rid of both issues.
