### ISSUE TITLE
A attempt to export cpg graph（have seen#247, solution miss）

### ISSUE THREAD

**Issue by HickeyHsu** [Fraunhofer-AISEC/cpg#776]
I've been following this amazing project for a long time.  I hope to extract cpg to files(.dot/.gml/.json) for deep learning usage. I noticed that #247 gave an solution"cpg-to-dot". However, this page was gone.

I'm wondering if there will be an official solution of cpg-export?

Thanks a lot!

**Comment by HickeyHsu** [comment]
I try to convert the result into jgrapht format, which can be easily export as different files. But I'm still struggling.

**Comment by oxisto** [comment]
> > I try to convert the result into jgrapht format, which can be easily export as different files. But I'm still struggling.
> 
> [https://github.com/HickeyHsu/SCPG](url) I make a demo to convert cpg into jgrapht format. Not a perfect attempt.

Cool idea!

**Comment by KuechA** [comment]
Closed by #1215
