### ISSUE TITLE
EOG is incorrect for assignments

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#79]
Consider this snippet:

```
int main() {
  int foo;
  Test t();
  foo = t.call();
}
```

I would expect the following EOG order: `int foo`-->`t()`-->`t`-->`call()`-->`foo`-->`foo = t.call()`. But in fact it is as shown in the image: `int foo`-->`t()`-->`foo`-->`t`-->`call()`-->`foo = t.call()`.

![eog-assignment](https://user-images.githubusercontent.com/1555755/76400195-2ff88000-6380-11ea-84a3-7eff9415aaa9.png)

**Comment by oxisto** [comment]
Hmm good questions, is there any hints about this in the C++ standard? For example if you have something like `a.b = c;`

**Comment by oxisto** [comment]
Ok looks like your assumption is correct at least for clang/LLVM. If you consider the following code:

```
#include <iostream>

int* get() {
  printf("get\n");
  int a;

  return &a;
}

int set() {
  printf("set\n");
  return 5;
}

int main() {
  int foo;

  *get() = set();
}
```

This will print:
```
set
get
```

**Comment by JulianSchuette** [comment]
Funnily, it is different for gcc:

```
get
set
[1]    21309 segmentation fault (core dumped)
```

I must admit the EOG might not be _incorrect_ per se here, but it is unexpected and makes DF analysis more complex.

**Comment by JulianSchuette** [comment]
Marking as quirk, closing.
