### ISSUE TITLE
Interfile analysis

### ISSUE THREAD

**Issue by dmitrylavrenov** [Fraunhofer-AISEC/cpg#80]
First of all, Thank you for such great tool.

I would like to ask the following questions. Does the tool allow to do interfile analysis?

**Comment by JulianSchuette** [comment]
It does. You may set any files or folders to analyze via the configuration:
```
File[] allMyFile = ... <HERE GO YOUR FILES> ...;
TranslationManager translationManager = TranslationManager.builder()
			.config(
				TranslationConfiguration.builder()
						.debugParser(false)
						.failOnError(false)
						.codeInNodes(true)
						.defaultPasses()
						.sourceLocations(allMyFiles))
						.build())
			.build();
translationManager.analyze().get();
```

**Comment by dmitrylavrenov** [comment]
I did it. 
How can I get edges between in the following case. For example, Sample1 class has a method "hello". In Sample2 class I call "hello" from Sample1. I would like to see DFG edges.

I've tried to create SubgraphWalker. But it is required to choose a specific file in "result.getTranslationUnits().get(0);"

`var config = TranslationConfiguration.builder().sourceLocations(path.toFile()).defaultPasses().registerPass(new ControlFlowGraphPass()).debugParser(true).build();

    var analyzer = TranslationManager.builder().config(config).build();
    var result = analyzer.analyze().get();
    var tu = result.getTranslationUnits().get(0);
    List<Node> graphNodes = SubgraphWalker.flattenAST(tu);`

**Comment by JulianSchuette** [comment]
Edges are creates by "Passes" and there is in fact no whole-program analysis pass that would create DFG (data flow graph) edges across methods/functions, let alone across RecordDeclarations (=the equivalent of a Java class, C++ class, or C/C++ struct). If you need interprocedural data flows, you would have to write an analysis on top of the current passes.

However, some passes such as `CallResolver` and `TypeHierarchyResolver` already operate across different RecordDeclarations and files.

The SubGraphWalker walks along the AST, which is inherently bound to a single file.

**Comment by dmitrylavrenov** [comment]
I've got it. Thank you for your answer!

**Comment by Masrepus** [comment]
Actually, interfile analysis is already supported. Consider the following example:

**Provider.java**
```java
public class Provider {

  public static int getValue() {
    return 42;
  }
}
```
**User.java**
```java
public class User {

  public void hello() {
    int value = Provider.getValue();
    System.out.println("Value: " + value);
  }
}
```

When accessing the graph programmatically, this might be a rather abstract experience, so I suggest you take a look at our Neo4j export tool [cpg-vis-neo4j](https://github.com/Fraunhofer-AISEC/cpg-vis-neo4j). This tool saves the internal Java representation of the CPG to the Neo4j graph database, which provides the Neo4j browser on port 7474 that displays the graph in a visual representation.

For the two files at hand, when feeding them into this visualization tool, we get the following:
![Screenshot from 2020-03-17 15-36-13](https://user-images.githubusercontent.com/6538121/76867575-fe8f2100-6865-11ea-8400-dfc27bad714e.png)

Here, we can see how the value `42` is passed along via a call to `Provider.getValue` to the `User.hello` function and is then stored into a variable. This value then goes on to be added to a string which is in turn passed to `System.out.println` as an argument. I have highlighted all DFG edges for better visibility.

As Julian already said, our call resolving mechanism already operates accross file boundaries, and I think this is the only real requirement for interfile dataflow analysis.

P.S.: If you want to access DFG edges programmatically without first persisting the graph to a dedicated graph database, take a look at `Node.prevDFG` and `Node.nextDFG`. These properties are converted to DFG edges upon persistance.
