### ISSUE TITLE
Decide `type` property for `FunctionDeclaration`

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#824]
Currently, the `type` property of a function declaration is (mostly) the returnType, which is additionally stored as a property. Wouldn't it make more sense to use a `FunctionPointerType` (or maybe a not-yet-existing `FunctionType`) for it?

**Comment by KuechA** [comment]
The type of a function should be (similar to) the function's signature. This means, it should consider the return value and the arguments (including their order), the modifier and maybe even the method and class name. This information is available in `FunctionPointerType`, so I think reusing that class would make sense.

The changes could probably break with some expectations of other tools if they rely on the current format, so it's probably a change for an API breaking version
