### ISSUE TITLE
FQN wrong for some static calls

### ISSUE THREAD

**Issue by titze** [Fraunhofer-AISEC/cpg#83]
For the following snippet, the fqn is `Cipher.getInstance(...)` but should be `javax.crypto.Cipher.getInstance(...)`

```java
import javax.crypto.Cipher;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

public class BCProviderCipher {

	public static void main(String[] args) {
		Cipher c4 = Cipher.getInstance("AES", new BouncyCastleProvider());
	}
}
```

This probably has something to do with `BouncyCastleProvider` not being available. But still, the CPG could "guess" the fqn quite easily here i imagine

**Comment by oxisto** [comment]
This could relate to a very old issue that we had where the Java parser would not resolve the use of a class as a symbol based on imports. Not sure if this was ever fixed or implemented.
