### ISSUE TITLE
as i am using this library to extract code property graph for my code files  in windows 10 but this tutorial is very confusing . would any of you elaborate it insimple steps so that i can use it in my research project as its very very urgent i request if any of you would be in touch with me to let me understand how to simply use this library

### ISSUE THREAD

**Issue by anushka192001** [Fraunhofer-AISEC/cpg#864]
# Stack trace

*Stack trace in case of an Exception*

# Unexpected behavior

*When the analysis terminates exception free but leads to unexpected graphs: Describe the difference between the generated graph and what you would have expected*

# Code of interest

```
codeOfInterest
```

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

*changes to or added components*

# Changes to the configuration

*configuration print*

**Comment by oxisto** [comment]
I guess you are referent to the `tutorial.md` right? We actually have a small video (https://www.youtube.com/watch?v=ngKtH6kYxx0) that goes through the steps of the tutorial. Problematic might be that we do not really support windows at this moment. Most of our developers use either Linux or Mac. It might work on windows, but we cannot really guarantee it.

Unfortunately, the overall documentation "how to use" this library is definitely something we need to improve.

**Comment by anushka192001** [comment]
thanks for providing this tutorial  to use cpg-console library 

https://www.youtube.com/watch?v=ngKtH6kYxx0 

i cloned the whole cpg directory
but when i am trying to do ../gradlew installDist its showing this error . 

![image](https://user-images.githubusercontent.com/63954873/184537774-62acc0e0-7229-4e2b-8a2f-dc152b2341a6.png)


![image](https://user-images.githubusercontent.com/63954873/184537782-9d14664e-429f-48cc-bde1-01b2ded84be1.png)


![image](https://user-images.githubusercontent.com/63954873/184537791-baa70e6e-3f81-4b7a-934b-6dfb4a8a3eb8.png)

**Comment by oxisto** [comment]
The Go frontend is now optional and should not be included by default if you clone the recent main branch.
