### ISSUE TITLE
when typed :export neo4j  after finally converting to cpgs using cpg-console ,got ERROR Application Unable to connect to localhost:7687, wrong username/password!  ,what does this mean?

### ISSUE THREAD

**Issue by anushka192001** [Fraunhofer-AISEC/cpg#872]
# Stack trace

*Stack trace in case of an Exception*

# Unexpected behavior

*When the analysis terminates exception free but leads to unexpected graphs: Describe the difference between the generated graph and what you would have expected*

# Code of interest

```
codeOfInterest
```

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

*changes to or added components*

# Changes to the configuration

*configuration print*

**Comment by anushka192001** [comment]
![image](https://user-images.githubusercontent.com/63954873/184544826-f671e9f7-b391-4e96-9ff3-c4d434261b6d.png)

**Comment by oxisto** [comment]
It means what it says :) `export neo4j` uses the default username with `neo4j` and password `password`. Are you able to change the neo4j password? Otherwise, I was anyway trying to make the username/password of `export` configurable.

**Comment by anushka192001** [comment]
So did you created any function or anything in your library? How can I change default user name and password to mine ?  @oxisto

**Comment by oxisto** [comment]
Closed by #873. It is now possible to specify username/password in export.
