### ISSUE TITLE
if this library can give me this type of CPG in any format? then it would be very helpful in my research project.

### ISSUE THREAD

**Issue by anushka192001** [Fraunhofer-AISEC/cpg#946]
![image](https://user-images.githubusercontent.com/63954873/197357897-8dcebc04-6967-48db-8588-beac56ca55c9.png)

like each  edge labelled with AST,PDG,CFG ?

i really this kind of format for my research project.

**Comment by oxisto** [comment]
> ![image](https://user-images.githubusercontent.com/63954873/197357897-8dcebc04-6967-48db-8588-beac56ca55c9.png)
> 
> like each edge labelled with AST,PDG,CFG ?
> 
> i really this kind of format for my research project.

We are using a different format, however you could use the library from shiftleft, which uses the format described in the paper https://github.com/ShiftLeftSecurity/codepropertygraph

**Comment by josepaiva94** [comment]
@oxisto Could you please provide a similar figure for the format used here?

**Comment by oxisto** [comment]
> @oxisto Could you please provide a similar figure for the format used here?

We are currently in the process of "formalising" our format a little bit and adding more documentation. Unfortunately, this is far from finished, but you can have a look at the already existing specification documents here: https://github.com/Fraunhofer-AISEC/cpg/tree/main/cpg-core/specifications

All nodes are modelled as Kotlin (Java) classes and you can find their properties here
- Declarations: https://fraunhofer-aisec.github.io/cpg/cpg-core/de.fraunhofer.aisec.cpg.graph.declarations/index.html
- Statements: https://fraunhofer-aisec.github.io/cpg/cpg-core/de.fraunhofer.aisec.cpg.graph.statements/index.html
- Expressions: https://fraunhofer-aisec.github.io/cpg/cpg-core/de.fraunhofer.aisec.cpg.graph.statements.expressions/index.html

**Comment by KuechA** [comment]
With #1171 , we will be able to automatically generate an overview of all nodes and their edges. The current result is already included in the [documentation](https://fraunhofer-aisec.github.io/cpg/CPG/specs/graph/) even if it's not complete yet

**Comment by konradweiss** [comment]
I will close this for now, as we have implemented an automated schema generation and have a additional description on out subgraphs: 

- [EvaluationOrderGraph-EOG](https://fraunhofer-aisec.github.io/cpg/CPG/specs/eog/)
- [DataFlowGraph - DFG](https://fraunhofer-aisec.github.io/cpg/CPG/specs/dfg/)
