### ISSUE TITLE
MultiValueEvaluator yields unexpected result when evaluating Expressions containing +=

### ISSUE THREAD

**Issue by MaximilianLincks** [Fraunhofer-AISEC/cpg#949]
# Unexpected behavior

I am trying to analyse the value of "s" in the println statement using a MultiValueEvaluator. The returned value for s is an ArrayList containing just the String "{+=}".

When the reassignment of s is done using ```s = s + "!"``` i recieve the expected result of an ArrayList containing ["small!","big!"]

# Code of interest

```
 int i = 3;
        String s;
        if(i < 2)
            s = "small";
        else
            s = "big";
        s += "!";
        System.out.println(s);
```

**Comment by oxisto** [comment]
Related to https://github.com/Fraunhofer-AISEC/cpg/issues/949, since the both follow the same logic.
