### ISSUE TITLE
DFG is not control-flow, context, or field sensitive

### ISSUE THREAD

**Issue by konradweiss** [Fraunhofer-AISEC/cpg#95]
The samples show that the DFG is not control flow sensitive. 
`
int a = 1;
if(args.length > 3){
      a = 2;
}else{
      System.out.println(a);
}
`
The usage of `a` in the print statement has a dfg edge to the declaration. The branch where `a` is used and where `a` gets the value `2` are mutually exclusive. There should be a DFG path from `1` to `a` but not from `2` to `a`.
In other words, the DFG edges currently are drawn intra-transactionally and are not transitive: paths of edges can not be considered to be true positive data-flows.
We could change the DFG-construction to follow the EOG and keep the last definitions of a variable, e.g. right-hand-side of an assignment, and draw edges between those.
So between the right-hand-side of a definition and the references in an expression where the variable is used. 
We have ongoing work where context and field-sensitivity will be solved as well, so this issue could be solved temporarily by the method described above, or by waiting until the more sophisticated approach with push-down systems or slicing is incorporated. 
![dfg_no_context_sensitivity](https://user-images.githubusercontent.com/12885000/81386499-5be07980-9115-11ea-8a25-cd526e322116.png)
![query_no_cfg_sensitivity](https://user-images.githubusercontent.com/12885000/81386506-600c9700-9115-11ea-86ef-abe27af412bc.png)
[DFGSample.zip](https://github.com/Fraunhofer-AISEC/cpg/files/4597807/DFGSample.zip)

**Comment by johspaeth** [comment]
I just read this issue and was curious, when I read context and field-sensitivity. I have been working on this form of data-flow for a while.
 
You may want to looked at https://github.com/CROSSINGTUD/WPDS, it might be adoptable to your problem as well. Feel free to contact me.

**Comment by konradweiss** [comment]
Thanks for your message :) we already took inspiration from the paper that you wrote, and a student is looking to adapt the approach to the CPG. We may come back to you, until then congratulations on the work you did on WPDS and greetings to the IEM.
