### ISSUE TITLE
Remove access to `LanguageFrontend` in passes

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#953]
A `LanguageFrontend` should only exist during parsing, however we use it currently in a very hacky way to transfer certain information to the passes. We should extract these information needed into a new class (e.g. `LanguageFeatures`) and make this available to every node. This would also solve certain issues with multi-language projects.

**Comment by oxisto** [comment]
Would also fix https://github.com/Fraunhofer-AISEC/cpg/issues/59

**Comment by KuechA** [comment]
See decisions in https://github.com/Fraunhofer-AISEC/cpg/blob/language-frontend-end/cpg-core/specifications/languageFrontendEnd.md for the implementation.
