### ISSUE TITLE
The Query API can only be accessed from Kotlin Code

### ISSUE THREAD

**Issue by MaxiLambda** [Fraunhofer-AISEC/cpg#961]
Many parts of the Query API can only be accessed from Kotlin Code due to reified arguments.
When using another JVM language you have to include Kotlin FIles in your Project to utilize the API.

Is it posible to fix this or do you have a clean workaround?

# Code of interest
from Query.kt
```
inline fun <reified T> Node.all(
    noinline sel: ((T) -> Boolean)? = null,
    noinline mustSatisfy: (T) -> Boolean
): Pair<Boolean, List<Node>> {
    val nodes = this.allChildren(sel)

    val failedNodes = nodes.filterNot(mustSatisfy) as List<Node>
    return Pair(failedNodes.isEmpty(), failedNodes)
}
```
thanks in advance

**Comment by oxisto** [comment]
Hmm to be honest, we are somewhat deprecating Java as a first-class citizen and moving towards more advanced Kotlin features. Mainly because Kotlin offers us a better and cleaner way to design a good API. Are there any blocking factors in using Kotlin in your project?
