### ISSUE TITLE
Super calls not resolved

### ISSUE THREAD

**Issue by Masrepus** [Fraunhofer-AISEC/cpg#99]
Example:
```java
public class A {
    public int getInt() {
        return 42;
    }
}

public class B extends A {
    @Override
    public int getInt() {
        return super.getInt() + 2;
    }
}
```

**Comment by oxisto** [comment]
I remember that there was an issue that I discovered in the Java Parser related to super-Calls not properly resolved. Apparently I did not open an issue on this, just discussed it on gitter. Might be worth finding out if this relates to that or if it is an issue specific to the CPG.

**Comment by Masrepus** [comment]
I figured that this might be somehow JavaParser related, as it is created as a static call, which makes little sense. But I will have to check the root cause in more detail. I would probably just fix it on our side for now, but we can surely pass this on to the JavaParser guys if it really is a problem coming from upstream :+1:

**Comment by oxisto** [comment]
Can you make a quick check whether this may be resolved in the latest JP version? There are some fixes related to super functions in 3.15.28+, we are at 3.15.10

**Comment by Masrepus** [comment]
`super.getInt()` is still resolved as a static call. Is there any changelog or do you need to go through all commits for that?

**Comment by oxisto** [comment]
I was looking at https://github.com/javaparser/javaparser/commit/5d63f63846f6049603771d4ff1928ba9fa0e98ab which sounded like in general super calls are resolved but not for specific cases

**Comment by Masrepus** [comment]
Ah I just double checked, the method itself is correctly resolved as `A.getInt`. So the problem is on our side as it seems
